ansible/ansible-navigator

- README.md
- ansible_navigator/action_runner.py
- ansible_navigator/actions/__init__.py
- ansible_navigator/actions/collections.py
- ansible_navigator/actions/config.py
- ansible_navigator/actions/inventory.py
- ansible_navigator/actions/run.py
- ansible_navigator/cli.py
- ansible_navigator/cli_args.py
- ansible_navigator/runner/api.py
- lint_and_check.sh
- setup.cfg
- share/ansible_navigator/markdown/help.md
- share/ansible_navigator/markdown/welcome.md
*  Add `run` subcommand with interactive and stdout mode
to invoke playbook
*  Remove `explore` and `playbook` command line option and
relevant changes
*  Refactor runner invocation code to use the new `run_command`
ansible-runner interface
*  Doc updates
> Add run action to support interactive and stdout mode

- .yamllint
- bindep.txt
- setup.cfg
- test-requirements.txt
- tests/smoketests/roles/assert_substring/meta/main.yml
- tests/smoketests/roles/assert_substring/tasks/main.yml
- tests/smoketests/roles/send_keys/defaults/main.yml
- tests/smoketests/roles/send_keys/meta/main.yml
- tests/smoketests/roles/send_keys/tasks/main.yml
- tests/smoketests/run.yml
- tox.ini
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/851
Change:
- Apparently if these tests are moved to a playbook, they're usable by
Zuul, now they're a playbook.
Test Plan:
- Tested the playbook several times in a clean CentOS 8 VM.
> Fix premature GHA nix; port smoketests to playbook

- ansible_navigator/actions/run.py
Fixes https://github.com/ansible/ansible-navigator/issues/120
If inventory source is not provided as for input within the user
form
> Fix single inventory source form prompt

- ansible_navigator/actions/inventory.py
- ansible_navigator/cli.py
- ansible_navigator/runner/api.py
*  Add support to run `ansible-inventory` command in
pass-through mode to work within local and execution
environment.
*  Refactor inventory action plugin to use new runner API's
for interactive and stdout mode
> Add support for inventory subcommand stdout mode

- ansible_navigator/actions/inventory.py
- ansible_navigator/actions/run.py
- ansible_navigator/app.py
- ansible_navigator/cli.py
- ansible_navigator/cli_args.py
- ansible_navigator/config.py
- share/ansible_navigator/markdown/help.md
- share/ansible_navigator/markdown/welcome.md
- Fixes #124, set :welcome to be interactive
- Move artifact file logic into run and add timestamp (issue #62)
- Update self.args in run always so artifact file uses current playbook name
- Add support for playbook in config
- Move re-argparse logic into base class for common use in inventory and run
- If using a form to prompt, run form back through arg parse to update args so if the user jumps to another action they are correct
- move the addition of parse_and_update into parse_and_update so when it's called from an action we will always have a complete args
- :inventory now requires -i just like the command line so it will pass through argparse correctly
> Simplify logic for reparsing command line

- ansible_navigator/cli.py
- ansible_navigator/utils.py
- docs/configuration.rst
- tests/unit/test_cli.py
- tests/unit/test_utils.py
- tox.ini
*  Add support to set ansible-naviagator configuration
file path using environment variable `ANSIBLE_NAVIGATOR_CONFIG`
*  Add support to read configuration file from `.yaml` and `.json` extension
* The first found matched directory path (based on order mentioned above) can have only one
valid configuration file. If in case more than one configuration files (with different
supported extensions) are found it will result in an error to avoid conflict
> Add configuration file path setting using env variable

- tests/integration/_common.py
This was inadvertently left over from an attempt to set the env var, setting it at the CLI in the tmux session was the only way that worked in the end, so monkeypatch is not needed here
> Remove unused monkeypatch

- ansible_navigator/configuration_subsystem/__init__.py
- ansible_navigator/configuration_subsystem/configurator.py
- ansible_navigator/configuration_subsystem/definitions.py
- ansible_navigator/configuration_subsystem/navigator_configuration.py
- ansible_navigator/configuration_subsystem/parser.py
- tests/unit/configuration_subsystem/data.py
- tests/unit/configuration_subsystem/test_navigator_configuration.py
- tests/unit/configuration_subsystem/test_navigator_configuration_previous_cli.py
- tests/unit/configuration_subsystem/test_sample_configurations.py
- tests/unit/configuration_subsystem/utils.py
An entry can now be flagged to only be carried forward is the subcommand is the same
Cleaned up the use of the enums
added tests
> Config subsystem: Better use of enums, add 'apply_to_subsequent_cli' logic and tests

- ansible_navigator/configuration_subsystem/__init__.py
- ansible_navigator/configuration_subsystem/configurator.py
- ansible_navigator/configuration_subsystem/definitions.py
- ansible_navigator/configuration_subsystem/navigator_configuration.py
- ansible_navigator/configuration_subsystem/navigator_post_processor.py
- ansible_navigator/configuration_subsystem/parser.py
- tests/unit/configuration_subsystem/data.py
- tests/unit/configuration_subsystem/test_navigator_configuration.py
- tests/unit/configuration_subsystem/test_navigator_configuration_entries_sanity.py
- tests/unit/configuration_subsystem/test_navigator_configuration_previous_cli.py
- tests/unit/configuration_subsystem/test_sample_configurations.py
- tests/unit/configuration_subsystem/utils.py
switch from use of Sentinel to Constant.NOT_SET
only set a default value if a default value was specified, otherwise leave NOT_SET
purge current configuration each time configurator.configure is run
organize test files better so they are grouped by like tests
> Centralize enums in configuration subsystem

- artifact.json
- pyproject.toml
- tox.ini
fixes #90 
it's a little noise but I would rather have this info when we need it
> add pytest duration, move cli options to toml

- setup.cfg
One thing to notice is that the `universal = 1` option usually requires `1` or `0`, not `True` / `False`.
Also, this project metadata says it's py3-only but marking the wheels as universal adds a `py2.py3`
tag effectively hinting to everyone that the content inside is compatible with Python 2 which is
incorrect.
> Fix py3-only wheel tags

- tests/unit/test_playbook_artifact_path.py
Fixes #216 
Should eliminate the pytest warning:
```
tests/unit/test_playbook_artifact_path.py:18
/Users/bthornto/github/ansible-navigator/tests/unit/test_playbook_artifact_path.py:18: PytestCollectionWarning: cannot collect test class 'TestData' because it has a __new__ constructor (from: tests/unit/test_playbook_artifact_path.py)
class TestData(NamedTuple):
-- Docs: https://docs.pytest.org/en/stable/warnings.html
```
> Rename TestData to TstData so pytest doesn't pick it up

- setup.cfg
Fixes #207 
Since controller integration has been removed for now, awxkit is no longer a dep
> rm unneeded awxkit from setup

- .vscode/settings.json
- docs/settings.rst
- utilities/doc_updater.py
the examples settings yaml file was not valid w/o the ---, restore it
fixes #228 
replaces 50% of #230 
approved by @relrod bwo #230
> [docs] restore dash to example settings file

- ansible_navigator/actions/run.py
Remove the space in the artifact filename by using an iso8601 timestamp
fixes #227 
replaces 50% of #230 
approved by @relrod bwo #230
> [:run] playbook artifact iso8601 timestamp

- tox.ini
fixes #272 
This allow the user to set XDIST_CPU for the desired number of CPUs to use for pytest-xdist.
> [tests] Allow setting of xdist cpu count

- ansible_navigator/configuration_subsystem/parser.py
Fixes #295 
- not using argparse choices since choice validation is handled in configurator
here's an examples of how the formatting looks:
```
optional arguments:
-h, --help            show this help message and exit
--ce CONTAINER_ENGINE, --container-engine CONTAINER_ENGINE
Specify the container engine (choices: 'podman' or 'docker') (default: 'podman')
--ecmd EDITOR_COMMAND, --editor-command EDITOR_COMMAND
Specify the editor comamnd (default: 'vi +{line_number} {filename}')
--econ EDITOR_CONSOLE, --editor-console EDITOR_CONSOLE
Specify if the editor is console based (choices: 'true' or 'false') (default: 'true')
--ee EXECUTION_ENVIRONMENT, --execution-environment EXECUTION_ENVIRONMENT
Enable or disable the use of an execution environment (choices: 'true' or 'false') (default: 'true') …
```
> [help] Add choices to argparse help string

- ansible_navigator/configuration_subsystem/navigator_post_processor.py
- ansible_navigator/utils.py
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>
If the inventory path in settings file had an env var, it was not being expanded, which also resulted in `abs_user_path()` prepending pwd to it.
> [configuration] Expand env vars in inventory path

- ansible_navigator/runner/api.py
- tests/integration/_tmux_session.py
*  While running testcase locally the user enabled
virtual env set the enviornment variable `VIRTUAL_ENV`
required for intial tmux session and the check for `.tox`
in not required in that case.
*  In CI run since virtual enviornment is enabled by `tox`
the `.tox` will always be presnet in the `VIRTUAL_ENV` path
and hence the check is not required
> Remove .tox check in VIRTUAL_ENV for tmux

- ansible_navigator/actions/_actions.py
Change:
- Otherwise every time an action is edited, navigator crashes if it is
open. This is because emacs will save files as .#something.py which
matched the filter previously.
Test Plan:
- Edited an action with emacs with navigator opened, and stopped getting
crashes.
> stop loading emacs swap files as actions

- ansible_navigator/configuration_subsystem/definitions.py
- ansible_navigator/configuration_subsystem/navigator_configuration.py
- ansible_navigator/configuration_subsystem/parser.py
Fixes #260
```
(venv) ➜  ansible-navigator git:(pass-through) python -m ansible_navigator doc --help                
usage: __main__.py doc [-h] [--ce CONTAINER_ENGINE] [--ecmd EDITOR_COMMAND] [--econ EDITOR_CONSOLE] [--ee EXECUTION_ENVIRONMENT] [--eei EXECUTION_ENVIRONMENT_IMAGE] [--la LOG_APPEND] [--lf LOG_FILE]
[--ll LOG_LEVEL] [-m MODE] [--osc4 OSC4] [--penv PASS_ENVIRONMENT_VARIABLE [PASS_ENVIRONMENT_VARIABLE ...]] [--senv SET_ENVIRONMENT_VARIABLE [SET_ENVIRONMENT_VARIABLE ...]] [--hd]
[-t PLUGIN_TYPE]
[plugin_name]
doc: Review documentation for a module or plugin
positional arguments:
plugin_name           Specify the plugin name
optional arguments:
-h, --help            show this help message and exit
--ce CONTAINER_ENGINE, --container-engine CONTAINER_ENGINE
Specify the container …
```
> [cli] Where applicable, add an epilog to each subcommand indicating the mapped ansible command parameters are supported

- tests/integration/_tmux_session.py
- tox.ini
- add a loop that ensures the tmux screen is the same for 5 captures before returning
- remove CPU throttle for tox.ini
- tested many times without intermittent failure
- this does add a couple minutes to the total test time, but some stability and consistency will be welcome
> [tests] tmux session improvements

- ansible_navigator/_version.py
- ansible_navigator/configuration_subsystem/parser.py
- ansible_navigator/initialization.py
- tests/unit/configuration_subsystem/test_sample_configurations.py
Fixes #313 
Fixes #314 
The version should be injected by the CI based on the repo tag eventually, so separating the collection doc cache schema version from the application version will eliminate the need for the application version to live in the code base
tests:
```
(venv) ➜  ansible-navigator git:(version) ansible-navigator --version           
ansible-navigator 0.6.2
10521101957.974 DEBUG 'ansible_navigator.main' Collection doc cache: 'current version' is '0.6.2'
210521101957.974 INFO 'ansible_navigator.main' Collection doc cache: version was empty or incorrect, rebuilding
210521101957.974 INFO 'ansible_navigator.main' Collection doc cache: 'current version' is '1.0'
```
> [cli] Add `--version` and split collection doc cache version from app

- ansible_navigator/initialization.py
- ansible_navigator/utils.py
- docs/settings.rst
- tests/smoketests/scenarios/test_user_config.yml
- tests/unit/test_utils.py
Look in CWD for `ansible-navigator` using `.yml` `.yaml` and `.json`
Look in ~ for `.ansible-navigator` using `.yml` `.yaml` and `.json`
merging of home onto cwd can come at a later date
system wide settings are no longer available
Fixes #293
> [settings] Simplify settings locations

- ansible_navigator/actions/collections.py
Fixes #342 
The search path order == precedence, don't sort it.
> [:collections] Collection search path order is important, don't sort

- ansible_navigator/configuration_subsystem/navigator_post_processor.py
- tests/unit/configuration_subsystem/test_invalid_params.py
@cidrblock It looks like the interactive code path behaves pretty differently (no doc validation for example), so I made plugin name optional for stdout mode only. Thoughts?
> [doc] support --list and --list_files with --mode stdout

- share/ansible_navigator/markdown/help.md
> [:help] Remove the :`ee-details` entry from the `:help`, sort

- ansible_navigator/actions/images.py
- share/ansible_navigator/markdown/help.md
Fixes #366
- also catch errors from the inspector
- add short entry `:im`
- change to bright blue, blue was too dark
> [:images] Param support for `:images`

- ansible-navigator.yml
- ansible_navigator/configuration_subsystem/navigator_post_processor.py
Fixes: #381 
- from the shell, cmdline is split via sys.argv
- from envvar. is a sting
- from settings file, is a string
- from a form, a list is sent to config subsystem
In the case cmdline is a string, shlex split it
tested locally from cli, env var, settings file, : prompt and form
> [settings] split cmdline if a string

- ansible_navigator/runner/api.py
Fixes https://github.com/ansible/ansible-navigator/issues/412
*  Ensure playbook is passed as first index in `cmdline` args
which ensure ansible-runner correctly identifies playbook
path and mount it within execution enviornemnt
> Fix run action issue when verbose flag passed

- ansible_navigator/utils.py
Change:
- This is mostly for macOS users who install ansible-navigator globally
and end up with a broken share path.
Test Plan:
- cidrblock tested it :D
Tickets:
- Fixes #433
- Fixes #261
> Add another path to share-dir search

- ansible_navigator/utils.py
Change:
- In get_share_directory(), include the directory in debug log messages.
- Also pull out some common log logic into a private helper function.
> [utils] include share directory in debug log

- ansible_navigator/app.py
Fixes #450 
Even if the collection's arg make it to another action with the collection doc cache mounted, subsequent action, will remove it prior to the deepcopy
> [:collections] Remove collection doc cache prior to deep copy

- ansible_navigator/ui_framework/curses_window.py
- ansible_navigator/ui_framework/form_handler_text.py
- ansible_navigator/ui_framework/ui.py
Fixes #444 
Based on limited testing with TERM=vt100, this allowed navigator to work, although with 0 colors
> [ui] Avoid traceback when TERM=vt100

- ansible_navigator/actions/collections.py
- ansible_navigator/actions/config.py
- ansible_navigator/actions/doc.py
- ansible_navigator/actions/inventory.py
- ansible_navigator/actions/run.py
- ansible_navigator/runner/api.py
- setup.cfg
- tests/unit/actions/test_run.py
Fixes https://github.com/ansible/ansible-navigator/issues/328
As par to PR https://github.com/ansible/ansible-runner/pull/689
the cwd parameter was renamed to host_cwd for sake of clarity
when running with execution environment.
> Update runner API cwd parameter name to host_cwd

- test-requirements.txt
Change:
- This is now required with newer mypy, it seems.
Test Plan:
- `tox -re type`
> [tests] add mypy type stub deps

- ansible_navigator/cli.py
- ansible_navigator/utils.py
Print a screen of blank lines for vscode (and others as they arise) to prevent bleed through of pre curses stdout/stderr in the TUI
> [ui] vscode trash fix, the appearance of clear

- ansible_navigator/actions/collections.py
- ansible_navigator/actions/config.py
- ansible_navigator/actions/doc.py
- ansible_navigator/actions/images.py
- ansible_navigator/actions/inventory.py
- ansible_navigator/runner/api.py
- setup.cfg
- tests/integration/test_stdout_exit_codes.py
Fixes https://github.com/ansible/ansible-navigator/issues/401
*  Add support to accept return code from runner API's
*  Modify config, doc, inventory, collection and images
action to get return code from runner API's
*  Update ansible-runner version to 2.0.0b1 which has
the corresponding runner changes
> Add runner return code in stdout mode

- ansible_navigator/actions/inventory.py
- ansible_navigator/actions/run.py
Fixes https://github.com/ansible/ansible-navigator/issues/457
Inventory can be a path, file, comma-separated list of hosts, or any string that meets a plugin's requirements.
This also fixes:
* Hosts without variables
* Empty inventory (shouldn't error by default if there are perhaps-unrelated warnings in stderr - INVENTORY_ANY_UNPARSED_IS_FAILED and INVENTORY_UNPARSED_IS_FAILED config options do that)
* Displaying fatal `ansible-inventory` errors
> Handle different types of inventory sources

- README.md
Change:
- This demonstrates 1RC1 by linking to a short, video-only screencast
that lives on YouTube. In the future, it might be better to have a
narrated screencast, but I don't have a narrator voice, so someone
else should do that.
Tickets:
- Fixes #199
> Update demo screencast for 1RC1

- ansible_navigator/actions/collections.py
- ansible_navigator/actions/images.py
Fixes: https://github.com/ansible/ansible-navigator/issues/490
Fixes: https://github.com/ansible/ansible-navigator/issues/492
In the case of an RPM, ansible-navigator will be in /usr.  These mounts don't get written to and are only ready from
tested locally fedora + podman/docker
Confirmed fix on rhel 8.4, with new RPM, selinux enforcing with both demo and ee supported images
> Remove label for utils mount

- ansible_navigator/_version.py
Following the 1.0.0 release, set main to 1.1.0a1 as the next anticipated version.
This can be adjusted as necessary based on changes
> main to 1.1.0a1

- ansible_navigator/yaml.py
Change:
- Remove explicit sort_keys which got passed to yaml.dump(). Old PyYAML did
not allow this kwarg. Old and new PyYAML both default to sorting keys, and
we never override that, so just remove the line and let PyYAML do its thing.
If we need to override it in the future, we can add a version check (though
it gets annoying to handle version comparisons manually).
Test Plan:
- Tested locally on PyYAML 3 and PyYAML 5.4.
Tickets:
- Fixes #517
- Fixes #522
- Fixes #525
> [yaml] remove explicit sort_keys

- ansible_navigator/actions/collections.py
- ansible_navigator/actions/config.py
- ansible_navigator/actions/doc.py
- ansible_navigator/actions/images.py
- ansible_navigator/actions/inventory.py
- ansible_navigator/actions/run.py
- ansible_navigator/configuration_subsystem/navigator_configuration.py
- ansible_navigator/configuration_subsystem/navigator_post_processor.py
- ansible_navigator/runner/api.py
- tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
- tests/integration/_action_run_test.py
- tests/unit/actions/test_run.py
- tests/unit/configuration_subsystem/data.py
This adds support for `container-options` so that ansible-navigator
can pass through container options to ansible-runner.
> Add support for container-options

- tox.ini
This reverts commit 48601e8df49c5240aad5ee96cf9b9bce7e8a50cb.
Depends-On: https://github.com/ansible/ansible-navigator/pull/571
> Revert "Drop `{tty}` and `{temp_dir}` substitutions"

- src/ansible_navigator/utils.py
Change:
- #562 broke people who run navigator from a clone of the repository
without installing it somewhere. The search path for the share
directory starts with looking for it relative to utils.py for exactly
this scenario. However when the ansible_navigator directory got moved
a level deeper, this path wasn't updated.
Test Plan:
- Ran ansible-navigator from git clone after pip uninstalling it.
> [utils] Fix share dir when running from repo clone

- share/ansible_navigator/utils/image_introspect.py
- tests/unit/test_image_introspection.py
@relrod noticed that if the Description of a package has a line starting with Name, it would break the package splitter
This specifies that the package delimiter is Name followed by spaces and a :, which is not perfect but better
Small unit test added to demonstrate the fix, which also caught an issue only one & the final package missing
Follow up on #614
> `:images` fix for `Name` in `Description`

- src/ansible_navigator/actions/run.py
fixes #598 with @cidrblock 's recommendation 
Worked with @alisonlhart was able to reproduce the issue and tested with steps listed in the issue. 
before 
```
Traceback (most recent call last):
File "/home/aubin/work/env/py38.0/bin/ansible-navigator", line 8, in <module>
sys.exit(main())
File "/home/aubin/work/env/py38.0/lib/python3.8/site-packages/ansible_navigator/cli.py", line 141, in main
return_code = run(args)
File "/home/aubin/work/env/py38.0/lib/python3.8/site-packages/ansible_navigator/cli.py", line 79, in run
return_code = run_action_stdout(args.app.replace("-", "_"), args)
File "/home/aubin/work/env/py38.0/lib/python3.8/site-packages/ansible_navigator/actions/_actions.py", line 109, in run_stdout
return action_cls(args).run_stdout()
File …
```
> set task duration to zero if None (fixes #598)

- .pre-commit-config.yaml
This cannot run in `pre-commit.ci` because it's too heavy.
> Only run flake8 on manual invocations

- .zuul.d/jobs.yaml
- .zuul.d/project.yaml
Adds back lint zuul job as non-voting until we can fix all linting errors.
Related: https://github.com/ansible/ansible-navigator/pull/665
> Reinstate linters zuul job

- docs/_ext/spelling_stub_ext.py
- src/ansible_navigator/utils.py
Fixes problems causing flake8, black and mypy to fail.
This is making `tox -e linters,type` pass, both of them were failing before this change as we had multiple pull-requests merged without running any linting in CI.
These fixes were originally included into https://github.com/ansible/ansible-navigator/pull/653 but I was asked to make them separately, even if it that would not allow proper testing on CI.
> Fix linting regressions

- tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/0.json
- tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/1.json
- tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/2.json
- tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/3.json
- tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/4.json
- tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/5.json
- tests/integration/actions/inventory/test_stdout_tmux.py
- tests/integration/actions/templar/base.py
The templar integration tests fail periodically, this _should_ fix that.
Since the file is `:opened` vim might be leaving a swap file:
```
'Found a swap file by the name '
'"~/src/github.com/ansible/ansible-navigator/tests/fixtures/integration/actions/run/.site.yaml.swp"',
'          owned by: zuul   dated: Tue Dec  7 18:52:13 2021',
'         file name: '
'~zuul/src/github.com/ansible/ansible-navigator/tests/fixtures/integration/actions/run/site.yaml',
'          modified: no',
'         user name: zuul   host name: '
'centos-8-stream-vexxhost-sjc1-000204357',
'        process ID: 76326 (still running)',
'While opening file '
```
The inventory integration tests fail periodically, this _may_ fix that.
- additionally add some look_fors to failing inventory test (as a test)
> [tests] Update 2 periodically failing tests

- .pre-commit-config.yaml
- docs/changelog-fragments.d/668.internal.md
This is fixing pre-commit.ci by avoiding two plugins which we did not
fully evaluate, one of them causing huge performance problems that
prevented use of pre-commit.ci and made local execution not practical.
We keep two other plugins as we already used them in order places and
they do not report problems.
> Move slow flake8 plugins to run manually

- docs/changelog-fragments.d/640.misc.md
- src/ansible_navigator/actions/run.py
- src/ansible_navigator/utils.py
- tests/unit/test_utils.py
depends-on: https://github.com/ansible/ansible-navigator/pull/671
Fixes #640 
- Without a guarantee of the runner duration value being an int, assume it can be either float or int, and round half up
- helper function added to utils
- unit test to help demonstrate the behavior of decimal
> [typing] Ensure `:run` passes rounded int to `utils.human_time`

- tox.ini
- This would enable pylint to run on the tests directory
- A number of other PRs have merged which cleaned up the test directory enough such that this should now be ok
> [lint] Add tests directory to pylint

- docs/_ext/spelling_stub_ext.py
This fixes an invalid formatting change introduced by #665.
> Fix the externally managed file by partialy reverting invalid "Fix linting regressions (#665)"

- .zuul.d/jobs.yaml
- .zuul.d/project.yaml
- playbooks/pre-run.yaml
As we no longer need to perform cross testing of
changes between ansible-runner and ansible-navigator
we remove that dependency.
This greatly improves the performance of zuul testing
and lower the resources usage as we no longer need
to wait for the container to be built.
> zuul: remove dependency on ansible-runner

- tox.ini
This is a less intrusive version of #677 that implements the same goals. I've skipped touching the non-tox section `[flake8]` because about to be moved out in a parallel effort. The comment reflow matches most of the other ones but changing long bash commands has also been skipped because editing them is scary (tox tends to break these if they are split incorrectly).
> Use a 2-line base indentation style @ tox sections

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/SECURITY.md
- .pre-commit-config.yaml
- docs/changelog-fragments.d/680.internal.1.md
- docs/changelog-fragments.d/680.internal.2.md
- docs/changelog-fragments.d/680.internal.3.md
- docs/conf.py
- docs/contributing/code_of_conduct.md
- docs/contributing/guidelines.md
- docs/contributing/security.md
- docs/index.md
This is mostly copy-paste and it intentionally skips polishing or debating on the standards. It is supposed to be a base that would be improved/reworded/refactored post-merge.
Preview: https://ansible-navigator--680.org.readthedocs.build/en/680/contributing/guidelines/
> Add initial CoC/contributing/security docs infrastructure

- .pre-commit-config.yaml
- .zuul.d/jobs.yaml
- .zuul.d/project.yaml
- tox.ini
- ensure that all optional pre-commit hooks are run with `manual`
- use `lint-vetting` as tox env name and job name for the run  linting with all optional hooks
- add non-voting zuul job named `lint-veting`
- normal run of `pre-commit.ci` will run only required/approved hooks, making its result relevant for the review process
> Add lint-vetting job for all optional linters

- bindep.txt
- test-requirements.txt
- tox.ini
Instead of running flake8 and yamllint in two different ways, we run pre-commit from tox -e linters. This allows
us avoid surprises cause by different tool versions.
The plan is to do the same for the other linters in follow-up.
> Ensure flake8 and yamllint run from pre-commit

- .gitignore
- .zuul.d/jobs.yaml
- test-requirements.txt
- tox.ini
Removes old tox -e type and relies on pre-commit. We still have
the report generated and available to tox -e report.
> Ensure mypy runs via pre-commit

- .darglint
This config explicitly specifies what is expected from the already
integrated linter plugin.
> Add a config for darglint

- tox.ini
The current pattern in the tests is
```
class BaseClass:
"""Base class for interactive collections tests."""
UPDATE_FIXTURES = False
```
which uses a capital constant
In case future developers decide to adhere to this:
https://wemake-python-stylegui.de/en/latest/pages/usage/violations/naming.html#wemake_python_styleguide.violations.naming.UpperCaseAttributeViolation
The grep was changed to case insensitive
> [tests] grep case insensitive UPDATE_FIXTURES

- tests/integration/actions/collections/base.py
- tests/integration/actions/config/base.py
- tests/integration/actions/doc/base.py
- tests/integration/actions/images/base.py
- tests/integration/actions/inventory/base.py
- tests/integration/actions/replay/base.py
- tests/integration/actions/run/base.py
- tests/integration/actions/stdout/base.py
- tests/integration/actions/templar/base.py
as suggested in #624 reduce complexity by presetting the var used in the condition.
Additionally, correctly set the pylint: disable statements for this function across tests, removing unneeded and adding new.
(this can be cleaned up more, #693 might be a good place to do that)
> [tests] Preset condition var

- .github/CONTRIBUTING.md
- .markdownlint.yaml
- .zuul.d/jobs.yaml
- docs/changelog-fragments.d/708.internal.md
- tox.ini
- use 'lint' instead of 'linters' for both tox and zuul jobs, so
they are consistent across all our projects. zuul job name is
already named `ansible-navigator-tox-lint` so it does not need change.
- remove leftover type from envlist in tox as it was removed, as is
part of lint.
- remove output lines from lint command that are not only outdated
but also irrelevant for docs inclusion.
> Use tox lint job and document it

- .zuul.d/jobs.yaml
- tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/0.json
- tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/4.json
- tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/8.json
- tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/1.json
- tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/5.json
- tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/9.json
- tests/integration/actions/config/base.py
- tests/integration/actions/config/test_direct_interactive_noee.py
- tests/integration/actions/config/test_welcome_interactive_noee.py
This changes the fialing tests such that they pass on both py36 and py37.
Because an older version of python may pull in an older version of ansible, we cannot directly compare the scrren contents for `:config` since the config options for different version of ansible may differ.
Only the `no ee` tests were failing because ansible was running outside the EE. Inside the EE the python version doesn't vary based on the version of python being tested... 
This adds "look_fors" for these tests (one near the top and one near the bottom of the output).
Also- renable the py36 and py37 tests so they are voting, and update fixtures to reflect the change from `compare_fixture` to simply looking for some strings on the screen. 
Related: https://github.com/ansible/ansible-navigator/pull/612
> Fix and enable tests with py36 and py37

- .pre-commit-config.yaml
- docs/changelog-fragments.d/736.internal.md
The 0.16.x stream is the first one compatible with flake8 v4.
> Bump flake8 WPS plugin to v0.16.0

- .github/CONTRIBUTING.md
- .pre-commit-config.yaml
- docs/changelog-fragments.d/727.internal.md
Make codespell implicit (required) in order to pass reviews.  
Errors found by codespell will need to be fixed for PRs to be merged if this is agreed to.
About [codespell](https://github.com/codespell-project/codespell):
Fix common misspellings in text files. It's designed primarily for checking misspelled words in source code, but it can be used with other files as well. It does not check for word membership in a complete dictionary, but instead looks for a set of common misspellings. Therefore it should catch errors like "adn", but it will not catch "adnasdfasdf". This also means it shouldn't generate false-positives when you use a niche term it doesn't know about.
Our configuration for it is here, it will be run by the precommit hook: …
> Make codespell an official linter

- tox.ini
This correct unintended bug introduced at https://github.com/ansible/ansible-navigator/pull/686/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449L52
Our intention was not to stop running the pre-commit hooks under
zuul. This brings the behavior in sync with our expectation and
documentation.
> Restore execution of pre-commit from inside tox -e lint

- docs/_ext/single_sourced_data.py
- src/ansible_navigator/_yaml.py
- src/ansible_navigator/actions/help_doc.py
- src/ansible_navigator/actions/log.py
- src/ansible_navigator/actions/open_file.py
- src/ansible_navigator/actions/run.py
- src/ansible_navigator/actions/welcome.py
- src/ansible_navigator/actions/write_file.py
- src/ansible_navigator/configuration_subsystem/configurator.py
- src/ansible_navigator/ui_framework/colorize.py
- src/ansible_navigator/ui_framework/curses_window.py
- tests/integration/actions/exec/base.py
Add explicit encoding to file operations. We already had this in several places but not on all.
Related: #742
> pylint: address unspecified-encoding rule

- tests/unit/runner/test_api.py
additionally add an `__init__.py` so it gets picked up with a vanilla `pylint tests` locally
> [lint] Fix lint issues in tests/unit/runner

- share/ansible_navigator/utils/catalog_collections.py
Making it consistent with others, fixes  W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
> [lint] Add encoding in share directory for file open

- share/ansible_navigator/utils/catalog_collections.py
- src/ansible_navigator/actions/config.py
Fix an unused variable in actions/config
Use the same approach in 2 other places. (improves the fix in #746)
Disable the import error in utils, since that directory isn't really a package, but instead catalog_collections is just a script that gets run, so a full or relative import couldn't be used in this case.
> [lint] Unused var and import error

- src/ansible_navigator/actions/inventory.py
- src/ansible_navigator/ui_framework/field_checks.py
- src/ansible_navigator/ui_framework/field_radio.py
- src/ansible_navigator/ui_framework/form.py
- src/ansible_navigator/ui_framework/form_utils.py
In the case of fields and options, both are dynamically created via a default factory.
The docs for E1101 state:
False positives: This message may report object members that are created dynamically, but exist at the time they are accessed.
http://pylint-messages.wikidot.com/messages:e1101
Although I could not find a mention for not-an-iterable (E1133), the assumption here is that it is also a false positive
> [lint] Fix pylint `no-member` and `not-an-iterable`

- .github/CONTRIBUTING.md
It's a follow-up for #737, it implements Brad's suggestion to show the example linting output ending.
> Mention the end of linting output in contributing

- src/ansible_navigator/configuration_subsystem/configurator.py
- src/ansible_navigator/configuration_subsystem/definitions.py
- src/ansible_navigator/configuration_subsystem/navigator_configuration.py
- src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
- tests/unit/configuration_subsystem/test_navigator_post_processor.py
I've pulled this out from my lint work, where it was needed, because it feels like it should be a separate change because we probably want it regardless.
This allows post processors to be delayed until after the first pass of post processors has been completed.
At that point, it will run the delayed ones. There is only one "level" of delay (so delayed post processors can't wait for a third pass). This is intentional, to keep things simple, otherwise we'd have a whole tree of post processors and it gets complex quickly.
Doing it this way just provides a simple way to say "this post processor depends on some other things that happen in the first pass, let's wait for this before we actually run it."
```
Change:
- Allow post-processors to be delayed until after the first
(alphabetical) pass. …
```
> [configuration] delayed postprocs, extra volmounts

- docs/requirements.in
The latest version of sphinx was causing the following errors, and therefore is being capped to version prior to the version causing the errors.
```
/home/docs/checkouts/readthedocs.org/user_builds/ansible-navigator/checkouts/774/docs/changelog.md:16: WARNING: hardcoded link 'https://github.com/twisted/towncrier' could be replaced by an extlink (try using ':gh:`twisted/towncrier`' instead)
/home/docs/checkouts/readthedocs.org/user_builds/ansible-navigator/checkouts/774/docs/installation.md:3: WARNING: hardcoded link 'https://github.com/containers/podman/issues/8016' could be replaced by an extlink (try using ':gh:`containers/podman/issues/8016`' instead)
```
Detailed information about the changes introduced in sphinx causing the errors can be found here:
Related: sphinx-doc/sphinx#10112 …
> Cap the version `Sphinx` below 4.4.0

- src/ansible_navigator/configuration_subsystem/configurator.py
- src/ansible_navigator/configuration_subsystem/definitions.py
- src/ansible_navigator/configuration_subsystem/navigator_configuration.py
- src/ansible_navigator/initialization.py
- tests/unit/configuration_subsystem/conftest.py
- tests/unit/configuration_subsystem/test_internals.py
- tests/unit/configuration_subsystem/test_previous_cli.py
- tests/unit/configuration_subsystem/test_sample_configurations.py
In order to present the current settings file path in `:settings`, we'll keep it in the internals.
Additionally, keep the source of how it was found.
A couple quick tests to ensure it get added.
> Store the settings file path for use later in the `:settings` action

- src/ansible_navigator/actions/inventory.py
The function that finds the maximum file modification time for file and directory based inventories had an unnecessary generator nested inside it.
This in turn eliminates a reported "missing trailing comma" error reported during the use of `tox -e lint-vetting`.
> Remove unnecessary generator inside inventory max modified times fuction

- setup.py
Make a small formatting change to the comment in setup.py.
This was necessary to eliminate an error thrown (E800) by `flake8-eradicate` which is one linter being vetted.
By reducing the errors thrown by `tox -e lint-vetting` it should allow future contributors to use it with needing to look through long lists of errors unrelated to their code, and see feedback related only to the changes being made in a PR.
> Small formatting change for comment in setup.py

- tests/unit/test_circular_imports.py
This changes 2 variable names in one test file such that they do not violate the `WPS111` rule as reported by the wemake style guide being vetted.
This should help users of `tox -e lint-vetting` identity errors related to the changes they may be proposing instead of needing to sift through errors unrelated to their changes.  
Before:
```
1     C812 missing trailing comma
1     RST304 Unknown interpreted text role "mod".
13    S101 Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
1     S404 Consider possible security implications associated with the subprocess module.
1     S603 subprocess call - check for execution of untrusted input.
2     S604 Function call with shell=True parameter identified, possible security issue.
2     WPS111 Found …
```
> Switch from short var names to longer in one test file

- .github/CONTRIBUTING.md
- .pre-commit-config.yaml
This enables a pre-commit hook to sort all import statements across the project so future contributors do not need to order them in a manner that is consistent with the repository. This should save all of us time and brain cycles during submissions and review.
Because `pre-commit` and `isort` will run automatically for every pull-request, it doesn't even need to be run locally as part of a developer workflow. (but can be with `tox -e lint`, so the changes can be seen locally)
- Remove the `stages: ['manual']` from the precommit entry, which will allow it to run when using `tox -e lint`
- Add `flake8-isort` as a required check after `isort` runs.
- Update contributors guide to reflect the use of isort
(this is a trust and verify approach, trust `isort` will do it's job, verify it did with …
> Enable automatic import statement sorting

- .pylintrc
- pyproject.toml
The resulting configuration in `pyproject.toml` should reflect what is needed now.
Having it in two places was confusing.
> Changes necessary to have the `pylint` configuration in only one location

- .flake8
This adds a few additional files to the `per-file-ignore` list within the flake8 configuration with an exemption for `S101` which is reported by `flake8-bandit` as part of the wemake style guide which is being vetted.
The list was also alphabetized to ensure new entries were placed in a sane location.
A note was added to the top of the flake8 per-file-ignores indicating that the glob for the tests folder ignoring s101 can be added later. Currently there is a conflict between globs and per-file entries.  See https://github.com/PyCQA/flake8/issues/670
This eliminates the `S101` entry from the output of `tox -e lint-vetting` so users of it can see messages only related to the changes they are making and not for files that were previously added to the repository:
```diff
1     C812 missing …
```
> Disable warnings related to the use of assert in the tests directory as reported with `lint-vetting`

- pyproject.toml
Fixes mistake in #800 
The list should have been a list with trailing commas in alphabetical order.
> Properly format `pylint` disable in `pyproject.yaml`

- .github/workflows/tox.yml
- tests/integration/actions/config/test_welcome_interactive_param_use.py
- tests/integration/actions/config/test_welcome_interactive_specified_config.py
This change aims to add a MVP implementation of GHA that replicates current zuul config.
Deliberately it does not include features that are not already covered by zuul jobs, and it also does not include a release pipeline.
The `look_nots` are being removed because `/home/runner` was used as a check in those tests to confirm that the test was not running in an EE.   Because GHA uses `runner` as the default user in it's images, we cannot use this test in the future.
> Add MVP GHA workflows

- src/ansible_navigator/ui_framework/field_button.py
- src/ansible_navigator/ui_framework/form_presenter.py
- src/ansible_navigator/ui_framework/validators.py
Form buttons should really only have one of 2 validators, either `all_true` in the case of a `Submit` button, or `none` in the case of a `Cancel` button.
This changes results in passing a `List` to the button's conditional validator rather than a `Generator`.
Several typing updates to correct what is being passed through.
This also eliminates a  trailing-comma error reported when using `tox -e lint-vetting`
> Form button validation, pass a `List` not `Generator`

- .flake8
When running `tox -e lint-vetting` a number of errors are reported by the wemake python style guide.
This moves those errors into the `per-file-ignore` list within the `flake8` configuration file.
No attempt was made to review or remediate the errors as WPS is just being vetted.
(`S101` was also added to account for #792 where needed when a per-file addition was newly added)
This should make it easier for users of `tox -e lint-vetting` to identify errors from linters being vetted for the changes they are making without needing to parse all errors that previously existed in the code.
Follow up PRs should be expected to migrate some per file ignores into the extended ignore list)
The list of errors was
```
src/ansible_navigator/action_runner.py:17:5: WPS436 Found protected module import: …
```
> Move `WPSXXX` errors reported by `lint-vetting` into `per-file-ignores`

- src/ansible_navigator/ui_framework/field_button.py
- src/ansible_navigator/ui_framework/form_defs.py
- src/ansible_navigator/ui_framework/validators.py
This is follow up to #790 which replaces the complex inline type with a predefined type.
As I was explaining it to @ssbarnea I realized this might be a better approach. (thanks for mentioning it sorin)
> Predefine `FieldValidatorState` and `FieldValidatorStates`

- pyproject.toml
This patch is necessary because `pylint` does not autoactivate third-
party plugins just because they are installed in the same virtualenv.
It seems like this bit of the original configuration got lost over
time: the Python distribution package is present in the dependencies
and gets installed but `pylint` does not use it. With this change, it
becomes used again.
> Activate `pylint-pytest` plugin

- tests/unit/test_circular_imports.py
These are reported by `flake8-bandit` which is part of the wemake-python style guide being vetted
Noting how and why subprocess was used seems reasonable here for future reviews that might see it.
```
tests/unit/test_circular_imports.py:14:1: S404 Consider possible security implications associated with the subprocess module.
import subprocess
^
tests/unit/test_circular_imports.py:104:1: S603 subprocess call - check for execution of untrusted input.
subprocess.check_call(imp_cmd)
^
```
Details can be found here: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_imports.html?highlight=B404 and here: https://bandit.readthedocs.io/en/latest/plugins/index.html#complete-test-plugin-listing
Note- The `flake8-bandit` extension changes the B to an S see …
> Disable 2 `flake8-bandit` checks (S404 and S603) in one unit test

- tests/unit/actions/test_exec.py
Given the possibility of some future static analysis tool misinterpreting `shell=True` as a subprocess parameter/call, it was changed here to read `use_shell`.
This also eliminates the 2 false positives being reported by `flake8-bandit` which is part of the wemake style guide being vetted.
```
tests/unit/actions/test_exec.py:34:1: S604 Function call with shell=True parameter identified, possible security issue.
shell=True,
^
tests/unit/actions/test_exec.py:49:1: S604 Function call with shell=True parameter identified, possible security issue.
shell=True,
^
```
> Rename `shell` to `use_shell` in one unit test

- .flake8
This adds `mod` to the user list of sphinx roles in the `flake8` file.  It was being reported by `flake8-rst-docstring` whcih is being vetted as it is included in the wemake style guide.
This was the error begin reported:
```
tests/unit/test_utils.py:1:1: RST304 Unknown interpreted text role "mod".
"""Test the functions exposed in the :mod:`~ansible_navigator.utils` subpackage."""
^
```
Some good info about this is here: https://github.com/peterjc/flake8-rst-docstrings/pull/16
> Add `mod` as permitted RST role

- share/ansible_navigator/utils/catalog_collections.py
- share/ansible_navigator/utils/key_value_store.py
- src/ansible_navigator/command_runner/command_runner.py
- src/ansible_navigator/configuration_subsystem/parser.py
- src/ansible_navigator/image_manager/puller.py
- src/ansible_navigator/tm_tokenize/grammars.py
- tests/integration/_action_run_test.py
This adds doc sting to the __init__ functions in 7 different files. the list is getting smaller so these are spread across multiple directories and subsystems.
This is part of a continuing effort to clean up documentation.
Note: param type was not added in anticipation of eventually being able to carry from forward form the type hints in the signature.
The flake8 file will be updated later when all D107 errors reported by flake8-pydocstyle (being vetted) are fixed.
> Add doc string to `__init__` in 7 files

- src/ansible_navigator/ui_framework/colorize.py
- src/ansible_navigator/ui_framework/curses_window.py
- src/ansible_navigator/ui_framework/form_handler_button.py
- src/ansible_navigator/ui_framework/form_handler_information.py
- src/ansible_navigator/ui_framework/form_handler_options.py
- src/ansible_navigator/ui_framework/form_handler_text.py
- src/ansible_navigator/ui_framework/form_handler_working.py
- src/ansible_navigator/ui_framework/form_presenter.py
- src/ansible_navigator/ui_framework/menu_builder.py
This adds doc sting to the `__init__` functions within the UI subsystem where missing.
This is part of a continuing effort to clean up documentation.
Note: param type was not added in anticipation of eventually being able to carry from forward form the type hints in the signature.
The `flake8` file will be updated later when all `D107` errors reported by `flake8-pydocstyle` (being vetted) are fixed.
> Add doc strings to `__init__` in the UI subsystem

- src/ansible_navigator/actions/run.py
This caused an error in #818 
```
/home/docs/checkouts/readthedocs.org/user_builds/ansible-navigator/envs/818/lib/python3.8/site-packages/ansible_navigator/actions/run.py:docstring of ansible_navigator.actions.run.Action._prepare_to_quit:: WARNING: more than one target found for cross-reference 'Interaction': ansible_navigator.ui_framework.Interaction, ansible_navigator.ui_framework.ui.Interaction
```
Eventually we would like to carry over the type hints in the signature, so this should be necessary.  (The link to Interaction and None does currently work, it just has to clicked above the return)
> Remove link in `actions/run.py` to Interaction

- tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/10.json
- tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/9.json
- tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/10.json
- tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/5.json
- tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/7.json
- tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/9.json
- tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/10.json
- tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/11.json
- tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/10.json
- tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/11.json
- tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/6.json
- tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/8.json
- tests/integration/actions/templar/base.py
Noticed in #812 , many of the test failures were related to the templar integration tests.
Several changes were made, hoping to reduce the number of failures
1) Exit vi after opening it, I don't suspect this made a difference, but it seem like a polite thing to do and was left in
2) Added a new local to the base class called, unmasked output, because we log locals, we should now see both the masked output and unmasked output from the tmux session if this happens again
3) Changes the search_within_response and look_for for the vi test to seach and look for something that was not previously on the screen, I suspect we were assuming vi had started when in fact we simply caught the `---` from the previous TASK screen
Fixtures were updated and added needed
Note: the files that were changes in …
> [tests] Changes to frequently failing templar integration tests

- .github/CONTRIBUTING.md
- .github/workflows/tox.yml
- .pre-commit-config.yaml
- tox.ini
This change exposes an additional vetting-like linting environment
that is limited to rules that are actively being addressed by the
contributors. This rules sub-list is to be kept small so that it
could be promoted put to voting and made enforced easily. Once the
rules are in a good shape, a new focused list of related rules can
take their place and become linting candidates.
> Introduce an intermediate lint-candidates target

- tox.ini
This adds a list of variables that we want to pass to tox
environments, some of them being critical for functioning of podman
and docker. Fixes the problem that prevented use of remote container
engines with tox.
The list was based on what we use on other similar projects, like
molecule-podman and molecule-docker.
> Add more vars to tox passenv

- .pre-commit-config.yaml
- tox.ini
This changes the `pylint` entry configured for pre-commit to be run as a native pre-commit hook rather than a local hook.
local hooks are described here:  https://pre-commit.com/#repository-local-hooks
Pros:
- pylint will now run automatically as a pre-commit hook for contributors that have installed the pre-commit hooks with `pre-commit install`
-  the version of the pre-commit hook as specified in the `rev` key is a reference to the version of the hook and in this case specifies the `pylint` version to use
- In the future, if necessary, the python version can also be specified in the pre-commit configuration if differences are found between the hook being run locally and via pre-commit
Cons:
- due to the nature of pre-commit hooks and caching, the dependencies and sometime their …
> Configure pylint to run as native pre-commit hook

- tox.ini
This allows us to limit the scope of testing, like `tox -e py -- -k test_graceful_failure`, a pattern that we use on all our pytest covered projects.
> Pass posargs to pytest on unit testing

- .flake8
- docs/_ext/single_sourced_data.py
- doc strings updated to reflect parameters in function signature
- descriptions updated to reflect functionality
- fix spelling mistakes as encountered
This additionally allows for the removal of D* and DAR* exceptions from the `flake8` configuration file for this file.
Please check for accuracy, as my understanding of the sphinx internals is limited.
> Documentation improvements in `docs/_ext/single_sourced_data.py` (D/DAR)

- pyproject.toml
- tox.ini
This simplifies pytest calling and also makes most coverage settings tox agnostic, so other tools can load them.
> Move most coverage options to pyproject.toml

- .github/workflows/tox.yml
```
The workflow is not valid. .github/workflows/tox.yml (Line: 5, Col: 10): Unexpected type of value '', expected type: String.
```
Fixes problem seen at https://github.com/ansible/ansible-navigator/actions/runs/1769433832/workflow
by using https://github.community/t/concurrecy-not-work-for-push/183068
> chore: fix concurrency condition for pushes

- .flake8
This relocates the f-string exemption from per file to the global ignore list.
- We allow the use of fstring, and prefer them
- This reduces the unexplained list of per-file exclusions
This particular message is from the unenforced, we-make-style guide which is being researched and vetted  
Related #717
> Move `f`-string check from per-file to global

- src/ansible_navigator/actions/exec.py
- tests/fixtures/integration/actions/exec/ansible-navigator.yaml
- tests/integration/actions/exec/test_stdout_config_file.py
Change:
- A misindentation caused 'ansible-navigator exec' to not actually get
env vars from config.
Test Plan:
- new integration
> [exec] *actually* set env vars from config

- .pre-commit-config.yaml
- go.sh
- pyproject.toml
Pylint was taking 30+s to run, this reduces it to less than 20.
- Remove pylint-pytest which is not currently needed
- Set jobs to 0 to use all CPUs
Details below
```
#!/bin/sh
for run in {1..5}
do
pre-commit run pylint --all-files -v | grep duration
sleep 5
done
---------------------------------------------------
Pre PR configuration:
- duration: 32.71s
- duration: 31.97s
- duration: 31.26s
- duration: 31.13s
- duration: 31.46s
Add pytest to dependencies in pyproject.toml:
- duration: 32.65s
- duration: 32.36s
- duration: 31.54s
- duration: 31.62s
- duration: 31.4s
Remove pylint-pytest from load_plugins and additional_dependencies:
- duration: 24.84s
- duration: 24.9s
- duration: 22.97s
- duration: 22.76s
- duration: 23.04s
Add jobs 0:
- duration: 17.15s
- duration: 16.91s
- duration: …
```
> Reduce pylint run time

- tests/integration/actions/templar/base.py
This adds a "search_within_response" to the steps that load a doc in the `templar` integration tests.
For those less familiar with the tmux tests, this is where we wait for a `search_within_response` value to be on the screen before looking for a `look_for` or simply return the response to compare against the fixture: https://github.com/ansible/ansible-navigator/blob/main/tests/integration/_tmux_session.py#L256
From https://github.com/ansible/ansible-navigator/issues/812 most of the recent failures are centered around the templar tests and loading a doc.
This has been run 18 times, with 2 failures unrelated to the `templar` tests, so I'm suggesting we merge this and reset the reporting in #812 from this point forward to identify new patterns.
> Decrease probability of false-positive `templar` integration test failures

- docs/changelog-fragments.d/863.bugfix.md
- src/ansible_navigator/image_manager/puller.py
- tests/unit/image_manager/test_image_puller.py
Change:
- Previously tag parsing broke if a port number for the registry was
specified as part of the image URL.
Test Plan:
- New unit test
Tickets:
- Fixes #843
> [image puller] fix tag parsing for port numbers

- .pre-commit-config.yaml
- Remove the `-v` flag from black since it was just noise and will by default report individual files
> Reduce black verbosity

- tests/integration/_tmux_session.py
- tox.ini
We've seen a couple of these in the tests recently:
```
if proc.stderr:
>           raise exc.LibTmuxException(proc.stderr)
E           libtmux.exc.LibTmuxException: ['server exited unexpectedly']
```
e.g. https://github.com/ansible/ansible-navigator/runs/5036171177?check_suite_focus=true
The message is coming from tmux itself, although raised by libtmux.
This includes some retry logic for the tmux session build, which is where the errors seem to be happening.
Each retry will be logged as warning like this (from a forced failure I created)
```
tests/integration/actions/templar/test_welcome_interactive_noee.py: 1 warning
/home/runner/work/ansible-navigator/ansible-navigator/tests/integration/_tmux_session.py:84: RuntimeWarning: tmux session failure #1: hello
warnings.warn(f"tmux session …
```
> Retry and warn for libtmux `server exited unexpectedly`

- tests/integration/actions/collections/test_direct_interactive_ee_with_volmount.py
This puts the one-line doc string on one-line.
This file was not in the flake8 files, so no changes necessary there.
> Documentation improvements in one `test_direct_interactive_ee_with_volmount.py` (D/DAR)

- tox.ini
- Reduce the verbosity of the pre-commit output, when needed it can be enabled locally with `tox -e lint -- --all-files -v`
> Reduce `pre-commit` verbosity in `tox.ini`

- .flake8
- .pre-commit-config.yaml
Clean-up was done in #651
This updates the .flake8 file to reflect those changes.
Additionally remove from pre-commit config, since this is the last occurance
(missed in #856 )
> Stop ignoring `D412` rule in the flake8 and precommit configurations

- pyproject.toml
- tests/integration/_cli2runner.py
- tests/integration/test_execution_environment.py
- tests/integration/test_execution_environment_image.py
- tests/integration/test_pass_environment_variable.py
- tests/integration/test_set_environment_variable.py
- tests/unit/actions/test_run.py
- tests/unit/configuration_subsystem/test_configurator.py
- tests/unit/configuration_subsystem/test_invalid_params.py
- tests/unit/configuration_subsystem/test_precedence.py
- tests/unit/configuration_subsystem/test_previous_cli.py
- tests/unit/test_cli.py
- tests/unit/test_log_append.py
This patch implements recommendations to use `pytest`-native fixtures
instead of importing `unittest`-world helper untilities directly using
a built-in `pylint` rule `preferred-module`.
> Guard against using unittest ecosystem within pylint

- src/ansible_navigator/_yaml.py
- test-requirements.txt
- tests/unit/test_yaml.py
This will ensure anchors and aliases are not used when we show content as yaml on the screen.
This was found during work for the `:settings` subcommand stdout ouput because several settings had some key-values in common and they were anchored and aliased.
Tests to confirm.
> Disable anchors and aliases when serializing to yaml

- .pre-commit-config.yaml
This removes the duplicate entry for pydocstyle from the pre-commit configuration.
Currently it is run via flake, included through the installation of the we make style guide.
This should reduce confusion and complexity for those cleaning up docstring violations about where thing should be removed and how doc string improvement suggestions are generated.
> Remove duplicate pydocstyle check from precommit configuration

- .pre-commit-config.yaml
This simply reformats the pre-commit config file to the defaults used by the RedHat yaml vscode plugin.
This was done to allow users of the RH yaml vscode plugin to enable "format on save" without needing to needing to be concerned about formatting scope creep in a PR intended to simply modify it's functionality.
Using the Redhat vscode plugin without overriding the defaults will also provide us insight to what many of our user's experience which is really valuable.
e.g. https://github.com/ansible/ansible-navigator/commit/f5d85ba6e1fbfcdad834242223b489877ede99ff
> Format the precommit file using RH vscode plugin defaults

- src/ansible_navigator/ui_framework/ui.py
- tests/integration/_interactions.py
- tests/integration/actions/builder/test_stdout_tmux.py
- tests/integration/actions/config/test_direct_interactive_ee.py
- tests/integration/actions/config/test_direct_interactive_noee.py
- tests/integration/actions/config/test_stdout_tmux.py
- tests/integration/actions/config/test_welcome_interactive_ee.py
- tests/integration/actions/config/test_welcome_interactive_noee.py
- tests/integration/actions/config/test_welcome_interactive_param_use.py
- tests/integration/actions/config/test_welcome_interactive_specified_config.py
- tests/integration/actions/exec/test_stdout_config_cli.py
- tests/integration/actions/exec/test_stdout_config_file.py
- tests/integration/actions/images/test_direct_interactive_ee.py
- tests/integration/actions/images/test_direct_interactive_noee.py
- tests/integration/actions/images/test_welcome_interactive_ee.py
- tests/integration/actions/images/test_welcome_interactive_noee.py
- tests/integration/actions/inventory/test_direct_interactive_ee.py
- tests/integration/actions/inventory/test_direct_interactive_noee.py
- tests/integration/actions/inventory/test_stdout_tmux.py
- tests/integration/actions/inventory/test_welcome_interactive_ee.py
- tests/integration/actions/inventory/test_welcome_interactive_noee.py
- tests/integration/actions/run/test_direct_interactive_ee.py
- tests/integration/actions/run/test_direct_interactive_noee.py
- tests/integration/actions/run/test_stdout_tmux.py
- tests/integration/actions/run/test_welcome_interactive_ee.py
- tests/integration/actions/run/test_welcome_interactive_noee.py
- tests/integration/actions/templar/test_direct_interactive_ee.py
- tests/integration/actions/templar/test_direct_interactive_noee.py
- tests/integration/actions/templar/test_welcome_interactive_ee.py
- tests/integration/actions/templar/test_welcome_interactive_noee.py
The word `indices` was misspelled in many locations, this corrects that.
> Correct spelling of indices throughout project

- tests/integration/actions/collections/base.py
- tests/integration/conftest.py
The word `independent` was misspelled. This corrects that.
> Correct spelling of independent

- src/ansible_navigator/ui_framework/curses_window.py
- src/ansible_navigator/ui_framework/ui.py
The word `support` was spelled incorrectly in a couple files, this corrects that.
> Correct spelling of support

- docs/_ext/single_sourced_data.py
- src/ansible_navigator/actions/builder.py
- src/ansible_navigator/actions/config.py
- src/ansible_navigator/actions/doc.py
- src/ansible_navigator/actions/exec.py
- src/ansible_navigator/actions/inventory.py
- src/ansible_navigator/actions/run.py
- src/ansible_navigator/configuration_subsystem/configurator.py
- src/ansible_navigator/configuration_subsystem/definitions.py
- src/ansible_navigator/runner/base.py
- tests/integration/_interactions.py
- tests/integration/test_pass_environment_variable.py
- tests/integration/test_set_environment_variable.py
- tests/unit/configuration_subsystem/data.py
- tests/unit/configuration_subsystem/test_fixture_sanity.py
- tests/unit/configuration_subsystem/test_precedence.py
- tests/unit/test_utils.py
Replace the use of envvar with env_var where possible.
The only exception is when referring to the ansible-runner key, which now has an inline or file exception for cspell.
(`cspell` is a spell checker for code https://github.com/streetsidesoftware/cspell which I hope to incorporate into my docstring updates process to eliminate introducing any additional spelling errors into the project.)
> Correct abbreviation of `environment variable` from `envvar` to `env_var` where possible

- tests/integration/actions/builder/base.py
- tests/integration/actions/builder/test_stdout_tmux.py
Builder was misspelled as `buidler` in a couple test files.  this corrects that.
> Correct the spelling of builder

- src/ansible_navigator/initialization.py
This also triggered the need to correctly type it.
The ignore is a result of 
```
src/ansible_navigator/initialization.py:30:5: error: Relative import climbs too
many namespaces  [misc]
from ...share.ansible_navigator.utils import KeyValueStore
```
Since the `KeyValueStore` def is in the share directory.
> Correct spelling of `collecion_cache` to `collection_cache`

- src/ansible_navigator/ui_framework/utils.py
Removes some unnecessary abbreviations and non-words in the file.
Checked the call to `convert_percentages` just to be sure it's not using keywords
```
for idx in indices:
convert_percentage(dicts[idx], cols, self._pbar_width)
```
> Remove abbreviations and non-words in `ui_framework/utils.py`

- src/ansible_navigator/ui_framework/menu_builder.py
- src/ansible_navigator/ui_framework/ui.py
This removes some abbreviates in the UI menu builder and removes the use of `dyct` in the same file.
One change in ui.py where the menu builder is initialized.
> Remove some abbreviations in menu builder

- share/ansible_navigator/utils/image_introspect.py
- Replace `cmd` with command
- Replaces `clss` with classes
- Replace `spoc` with single_process
- Replace `mproc` with multi_process
> Remove abbreviations for `command` and `classes` and process types in `image_introspection.py`

- share/ansible_navigator/utils/catalog_collections.py
- src/ansible_navigator/actions/collections.py
This unabbreviates a few words in catalog_collections.py.
The only exception is where the final entry is built, as we need to carry forward the abbreviation from here:
https://github.com/ansible/ansible/blob/15ace5a854886cd75894e7214209e4b027034bdb/lib/ansible/galaxy/collection/__init__.py#L807
collections.py was changed as it is the recipient of the data.
Additional testing was done locally to ensure there were not issues with an existing collection cache as a new one is generated with our CI testing each time.
The checksum dictionary is not stored in the collection cache, so we don't require a version change of it here, only the checksum is used as the key in the collection cache.... whew.
> Unabbreviate chksum, fpath, cname in catalog_collections.py

- src/ansible_navigator/action_runner.py
- src/ansible_navigator/ui_framework/curses_window.py
- src/ansible_navigator/ui_framework/form_presenter.py
- src/ansible_navigator/ui_framework/menu_builder.py
- src/ansible_navigator/ui_framework/ui.py
This normalizes the way we refer to the height and width of both the screen and viewport.
There was a mix of x,y,_h,_w.  It is simply width and height now throughout.
Testing of resize, scrolling and refresh were done locally, in addition to the coverage GHAs will provide for rendering.
> Normalize references to screen/viewport height and width

- tests/unit/actions/test_config.py
This replace the use of dval and cval with default_value and current_value in one test file.
> Remove dval and cval from test_config

- src/ansible_navigator/actions/run.py
- src/ansible_navigator/steps.py
- src/ansible_navigator/ui_framework/curses_window.py
- src/ansible_navigator/ui_framework/menu_builder.py
- src/ansible_navigator/ui_framework/ui.py
- src/ansible_navigator/utils.py
This removes rtype from several functions which had a duplicate return type.
For 2, a return type was added.
This is not every one in the repo, as other's require cascading type work.
> Remove rtype from docstrings

- tests/integration/_common.py
- tests/integration/_interactions.py
This removes the code replaced in #972
- The `Step` class should no longer be used
- No tests should have a `look_fors` attribute now
> Remove unneeded code in tests 

- tests/integration/actions/builder/base.py
Some timeouts have been seen https://github.com/ansible/ansible-navigator/runs/5162080013?check_suite_focus=true#step:7:3528
and in here: https://github.com/ansible/ansible-navigator/issues/812
> Allow 10 minutes for a builder build

- src/ansible_navigator/utils.py
This fixes a small inconsistency introduced in https://github.com/ansible/ansible-navigator/pull/926
where the type hint didn't match the type specified in the doc string.
I missed it :(
> Remove conflicting type in docstring

- docs/changelog-fragments.d/948.feature.md
- src/ansible_navigator/actions/run.py
Fixes #303 
This can last a second or 2, or less? depending on the development system and it's speed.
Users will see this until the first message is received from runner.
Tested locally with and with out an EE.  Intentionally not added to the tests because of risk of it being missed on the screen.
> Notification in `run`: Preparing for automation, please hold on

- src/ansible_navigator/action_base.py
- src/ansible_navigator/action_defs.py
- src/ansible_navigator/actions/__init__.py
- src/ansible_navigator/actions/_actions.py
- src/ansible_navigator/actions/builder.py
- src/ansible_navigator/actions/config.py
- src/ansible_navigator/actions/doc.py
- src/ansible_navigator/actions/exec.py
- src/ansible_navigator/actions/inventory.py
- src/ansible_navigator/actions/run.py
- src/ansible_navigator/cli.py
- tests/integration/_action_run_test.py
- tests/integration/test_stdout_exit_codes.py
Fixes #291
This normalizes the output of `run_stdout` across all actions to be predefined NamedTuple where a string is something needing to be displayed via stderr or stdout based on the return code.
Note that, there is no case where we do this by design, but it was accounted for in the `builder` action, so rather than have one be slightly different, the write of messages was moved up to `cli.py` and all actions may now return a string.
Tests updated to account for the return.
> Normalize stdout return from actions

- src/ansible_navigator/utils.py
The ExitMessage class was converted to a dataclass.
Added to and corrected the documentation of it.
> Convert ExitMessage to a  dataclass

- .darglint
- .flake8
- .pre-commit-config.yaml
- src/ansible_navigator/ui_framework/form_handler_text.py
- test-requirements.txt
- tox.ini
No changes in this PR should effect the current enforced configuration or the outcome of developers/CI runs using `tox -e lint`
The goal of vetting has always been to both vet different tools, workflows and configurations.  Based on what we've learned I believe this configuration draws more attention on those linters actively being remediated.
This positions us to incrementally add new linters that are interesting, do the clean up and show the positive results, without boiling the ocean and over complicating the configuration prior to enforcing a new one.
Additionally, this should improve the developer experience by:
1) Making lint-candidates an all in one check prior to a PR
2) Allow for IDE feedback for the linters being vetting by install the python packages for the flake8 extentions …
> Ensure tox configuration focuses on docstrings and developer experience

- .github/workflows/tox.yml
- tox.ini
Necessary because it is now running the full suite of pre-commit checks.
Resolves an issue introduced in #973 
This is the error seen: https://github.com/ansible/ansible-navigator/runs/5250061633?check_suite_focus=true#step:7:34
> Set the python version for lint-candidates to 3.10 in GHA

- .pre-commit-config.yaml
- cspell.config.yaml
- mypy.ini
This PR moves the mypy configuration out of the `.pre-commit-config.yaml` into `mypy.ini`
- Added entry to not spell check the `mypy.ini` file with cspell.
More PRs to follow related to the configuration.
Related #977
> Move mypy configuration to mypy.ini

- .pre-commit-config.yaml
- tests/integration/actions/run_unicode/base.py
- tests/unit/test_yaml.py
Ongoing work to remove ignore-imports. from the mypy configuration.
One type fix and one ignore with explanation.
> Add pytest to mypy dependencies in pre-commit

- .pre-commit-config.yaml
- mypy.ini
- Eliminates the need for lxml pinned to a version incompatible with sphinx
- I don't think anyone was using this, was added early on in #111
> Remove mypy txt report

- .pre-commit-config.yaml
- docs/conf.py
- mypy.ini
- test-requirements.txt
Ongoing effort to remove ignore-imports from mypy.
- Added as a dependency in the precommit entries for python3.6 and 3.10
- Added to test-requirements so mypy can be used from the command line
- One type ignore b/c sphinx spelling is not typed.
> Add sphinx to mypy deps in pre-commit and test-requirements

- .github/chronographer.yml
When the list in the config is explicit, then only those bots get ignored but now PRs from any GitHub Apps will not require change notes.
> Ignore PRs from any GitHub apps in Chronographer

- src/ansible_navigator/cli.py
- src/ansible_navigator/configuration_subsystem/navigator_configuration.py
- src/ansible_navigator/configuration_subsystem/parser.py
- tests/unit/configuration_subsystem/test_previous_cli.py
- tests/unit/configuration_subsystem/test_sample_configurations.py
Rather than importing `_version` from multiple locations, simply  populate the `NavigatorConfiguration.application_version` and use that.
In the case a `_version.py` file is not available, simple use the default value of `Constants.NOT_SET`
> Limit use of `_version.py` to one location

- .flake8
- src/ansible_navigator/utils/key_value_store.py
- tests/unit/utils/__init__.py
- tests/unit/utils/conftest.py
- tests/unit/utils/test_key_value_store.py
This remediates some new errors found by the linters and spelling checker being tried out.
**This was not in scope for the original PR because none of these are enforced.**
The `__init__.py` was added so pylint traverses the directory.
Related #988 (for reference only)
> Follow up to KeyValueStore PR (pylint, docstrings, spelling) (D/DAR)

- docs/conf.py
- src/ansible_navigator/actions/open_file.py
- src/ansible_navigator/actions/run.py
- src/ansible_navigator/actions/write_file.py
- src/ansible_navigator/ui_framework/ui.py
- src/ansible_navigator/utils/serialize.py
Centralizes the json dumping into one location, to prevent issues like the below and will allow for a different encoder in one place.
Fixes #1003 
(yaml can be moved into this file as well to centralize all serializers)
> Centralize json dump and dumps

- share/ansible_navigator/utils/catalog_collections.py
The file only exists when running in an EE, not during type checking.
Not previously caught as we still ignore import errors, this is another small fix on the path to remove that.
> Reorder import of key_value_store

- .readthedocs.yml
This aligns the RTD config to the spec of their json schema file.
Formatting changes to align with the RH yaml extension/LS
Additionally upgrade the interpreter version to 3.10.
Also alphabetized the entries, with the exception of the version which was relevant to the comment up to.
> Align the RTD config file to the schema, upgrade to python 3.10 

- .pre-commit-config.yaml
- pyproject.toml
The pyproject.toml file was fist sorted using: https://pypi.org/project/toml-sort/
Some comments had to be restored after that, but it was a good start.
The remaining change were made by the toml plugin for prettier.
Works well with: https://marketplace.visualstudio.com/items?itemName=bodil.prettier-toml
Related: https://github.com/ansible-community/devtools/issues/31
> Add toml support to prettier

- .pre-commit-config.yaml
- mypy.ini
This removes the `ignore_missing_imports` for mypy, and accommodates `setuptools_scm` which is required now for doc/conf.py.
> Remove ignore missing imports for mypy

- docs/_ext/single_sourced_data.py
- docs/conf.py
- mypy.ini
- share/ansible_navigator/utils/catalog_collections.py
- src/ansible_navigator/runner/ansible_config.py
- src/ansible_navigator/runner/ansible_doc.py
- src/ansible_navigator/runner/ansible_inventory.py
- src/ansible_navigator/runner/base.py
- src/ansible_navigator/runner/command.py
- src/ansible_navigator/runner/command_async.py
- src/ansible_navigator/tm_tokenize/reg.py
Centralize the mypy ignore import statements into the mypy.ini file.
This will make it easier to maintain, explain and audit the 3rd packages that are not typed.
One type was clarified as well, to ensure it doesn't get researched as an import error in the future.
> Centralize mypy `ignore[import]` statements

- src/ansible_navigator/ui_framework/colorize.py
- tests/unit/ui_framework/test_colorize.py
https://github.com/ansible/ansible-navigator/commit/c92f3b81f3b01910b7d37b43f476f5a10f296def#diff-3d34285d5669d838670a1586c158a7bd0b1087b93a5e1f4a625288dda34cb28fL159
Originally, if the color was `None` we simply returned `None` and continued resolution past font style, until  color was found.
When the conditional was removed, and an intermediate fontstyle was found in the scope:
` color={'scope': 'strong', 'settings': {'fontStyle': 'bold'}}`
The foregound color was `None` and the following occurred:
```
File "/Users/rick/dev/ansible/ansible-navigator/src/ansible_navigator/ui_framework/colorize.py", line 178, in hex_to_rgb
value = value.lstrip("#")
AttributeError: 'NoneType' object has no attribute 'lstrip'
```
The fix is to continue resolution until a scope entry with a foreground color …
> Fix color resolution issue

- src/ansible_navigator/ui_framework/ui.py
This change is being broken out of #957 to reduce what is found in that PR. 
In preparation for the UI taking a list of dataclasses in addition to a list of dictionaries, we need to make sure we are not assuming the objects in the list are subscriptable and instead use a get method against them.
Although not an ideal long term stance, any dataclass provided to the UI will need to support a `get()`.
Rather than add a `super()._getattribute__` this felt like a cleaner approach:
```
@dataclass
class Data:
a: int
b: int
def __getitem__(self, key):
return super().__getattribute__(key)
def get(self, attr):
return getattr(self, attr)
t1 = Data(1, 2)
t1["a"]  # calls __getitem__
t1.get("a") # call get
```
> Prefer `thing.get(key)` over `thing[key]` in ui.py

- .pre-commit-config.yaml
It conflicts when the PEP257 attribute naming convention is used to document either a `TypeAlias` or `NewType`.
Related: https://github.com/pre-commit/pre-commit-hooks/issues/159
```String literals occurring immediately after a simple assignment at the top level of a module, class, or __init__ method are called "attribute docstrings".```
Ref: https://www.python.org/dev/peps/pep-0257/#id4
As seen here: https://results.pre-commit.ci/run/github/320052445/1646080610.D81bOX7LQLakCKvAoaxx_A
because of:
https://github.com/ansible/ansible-navigator/pull/1024/files#diff-876f32fdc126136789ecfd4484fd9e4950a5faf7fb8fa3cefcff7ac6f6b7ac50R27
> Remove docstring first check from pre-commit

- docs/changelog-fragments.d/952.feature.md
- src/ansible_navigator/cli.py
- src/ansible_navigator/configuration_subsystem/navigator_configuration.py
- src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
- src/ansible_navigator/image_manager/puller.py
- src/ansible_navigator/utils/functions.py
- src/ansible_navigator/utils/key_value_store.py
- tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
- tests/unit/configuration_subsystem/data.py
- tests/unit/image_manager/test_image_puller.py
Fixes #505 
Fixes #632 
This add a `--pull-arguments` command line parameter which will pass additional args to the pull policy command.
- json schema updates WIP: https://github.com/ansible-community/schemas/issues/150
- test updates
- shortened `pull_policy` to `policy` in puller to match incoming `arguments`
This turns `pull` into a dictionary, `pull-policy` will need to be changes, and will cause a major release
See: https://github.com/ansible/ansible-navigator/issues/951
> Add pull_arguments

- docs/changelog-fragments.d/1029.breaking.md
- src/ansible_navigator/configuration_subsystem/navigator_configuration.py
- tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
This moves pull policy under the pull key in the settings file.
This will result in the next release being a major as it is a breaking change.
Fixes #951
> Move pull_policy to pull.policy

- .github/SECURITY.md
- .prettierignore
Controlling the line length was a manual step, but it should be fine moving forward.
> Allow prettier to format security.md

- tests/integration/_tmux_session.py
Ran into some issues with tmux reporting a failure or pass when it was the opposite. this clears the screen to ensures things will be accurately represented.
> Clear tmux screen in case subsequent tests produce the same output

- src/ansible_navigator/command_runner/command_runner.py
- src/ansible_navigator/image_manager/inspector.py
- tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/0.json
- tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/1.json
- tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/0.json
- tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/1.json
- tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/1.json
- tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/2.json
- tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/1.json
- tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/2.json
Just to ensure the data structure is not abused in the future.
> Switch from `SimpleNamespace` to `dataclass` in command runner

- src/ansible_navigator/image_manager/puller.py
Just to ensure the data structure is not abused in the future.
> Switch from `SimpleNamespace` to `dataclass` in puller

- src/ansible_navigator/actions/collections.py
- src/ansible_navigator/actions/config.py
- src/ansible_navigator/actions/doc.py
- src/ansible_navigator/actions/images.py
- src/ansible_navigator/actions/inventory.py
- src/ansible_navigator/actions/run.py
- src/ansible_navigator/ui_framework/colorize.py
- src/ansible_navigator/ui_framework/curses_defs.py
- src/ansible_navigator/ui_framework/form_handler_text.py
- src/ansible_navigator/ui_framework/form_presenter.py
- src/ansible_navigator/ui_framework/menu_builder.py
- src/ansible_navigator/ui_framework/ui.py
Allows them to be used as if they were an instantiated class rather than referred to as an alias.
It cleans up the definitions and return values.
Minimal code change were made, limited to a var name change for consistency or the way the return value was generated.
TIL, Changed in version 3.10: NewType is now a class rather than a function. There is some additional runtime cost when calling NewType over a regular function. However, this cost will be reduced in 3.11.0.
https://docs.python.org/3/library/typing.html#newtype
> Define `CursesLine` and `CursesLines` as NewType (`:settings` related)

- .config/dictionary.txt
- cspell.config.yaml
A couple updates for the unenforced cspell pre-commit hook:
1) Remove entries from the exception dicitonary that are now availble
2) Remove the use of the cpp dictionary, since it has a number of misspelled words 
```
definitition
definiton
definitons
defintion
defintions
defitions
```
https://raw.githubusercontent.com/streetsidesoftware/cspell-dicts/main/dictionaries/cpp/cpp.txt
> cspell maintenance

- docs/conf.py
- src/ansible_navigator/steps.py
- tests/unit/test_typestep.py
Introduces dataclass `TypedStep` into steps.py for use in :settings action and future actions. Existing actions may be refactored at a later date to use `TypedStep` instead of `Step`. 
Added unit tests to test`TypedStep` property and setter methods in tests/unit/test_typestep.py. Tests are not parameterized currently as the unit tests are only asserting initial and post-setter values for one TypedStep object.
> Building dataclass `TypedStep` into steps.py and building `TypedStep` unit tests (`:settings` related)

- src/ansible_navigator/ui_framework/content_defs.py
- src/ansible_navigator/ui_framework/utils.py
- tests/unit/ui_framework/test_progress_bar.py
Depends on #1014 
The `Any` here should be replaced with `ContentBase` when it merges.
This is a rewrite of the convert percentages function to account for the data being either a dictionary or dataclass.
New tests to confirm.
> Convert percentages, dataclass capable (`:settings` related)

- docs/conf.py
- src/ansible_navigator/actions/open_file.py
- src/ansible_navigator/actions/run.py
- src/ansible_navigator/actions/write_file.py
- src/ansible_navigator/ui_framework/ui.py
- src/ansible_navigator/utils/serialize.py
- tests/unit/actions/test_run.py
- tests/unit/ui_framework/test_colorize.py
- tests/unit/utils/test_serialize_yaml.py
- tests/unit/utils/test_unserializable.py
Migrate to the serialization function(s) across the project.
- Added `serialize_write` and `serialize_write_temp` to central the logic into one place.
- Necessary changes to UI, open, run, and write actions
- Ensure everything coming and going from serialize is now a ``Path``
- Updated tests to use serialize rather than json directly for additional coverage
- Made an attempt to narrow down the types, but it tricky when we allow `:{{ some_nested_thing }}`
- Removed the double open of files
- Additional testing done locally accessing nested data, opening and writing files
- Switch to SafeDumper for yaml, add related tests for both serialization formats.
Closes #971 
Closes #499
> Migration to serialization (`:settings` related)

- .github/release-drafter.yml
- .github/workflows/ack.yml
- .github/workflows/push.yml
This will help us see exactly what was merged into the main branch so we will know what version number we should use for next release.
> Add release drafting pipelines

- docs/changelog-fragments.d/1100.breaking.md
- src/ansible_navigator/configuration_subsystem/navigator_configuration.py
- src/ansible_navigator/configuration_subsystem/schema.py
- tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
This will enable help_playbook to be moved under ansible.playbook.help
More to follow this to get the settings file in order for 2.0
> Move playbook to playbook.path

- docs/changelog-fragments.d/1099.feature.md
- setup.cfg
- src/ansible_navigator/configuration_subsystem/configurator.py
- src/ansible_navigator/configuration_subsystem/navigator_configuration.py
- src/ansible_navigator/configuration_subsystem/transform.py
- src/ansible_navigator/utils/json_schema.py
- test-requirements.txt
- tests/fixtures/integration/actions/replay/ansible-navigator.yml
- tests/fixtures/integration/execution_environment/ansible-navigator_empty.yml
- tests/fixtures/integration/execution_environment_image/ansible-navigator_empty.yml
- tests/fixtures/integration/pass_environment_variable/ansible-navigator_empty.yml
- tests/fixtures/integration/set_environment_variable/ansible-navigator_empty.yml
- tests/fixtures/unit/cli/ansible-navigator.yml
- tests/fixtures/unit/cli/ansible-navigator_empty.yml
- tests/fixtures/unit/configuration_subsystem/ansible-navigator_empty.yml
- tests/fixtures/unit/configuration_subsystem/ansible-navigator_unknown_key.yml
- tests/integration/settings_from_cli/__init__.py
- tests/integration/settings_from_cli/test_json_schema_errors.py
- tests/unit/configuration_subsystem/conftest.py
- tests/unit/configuration_subsystem/test_broken_settings.py
- tests/unit/configuration_subsystem/test_internals.py
- tests/unit/configuration_subsystem/test_invalid_params.py
- tests/unit/configuration_subsystem/test_json_schema.py
- tests/unit/test_cli.py
- Added JSON schema as a hard dependency
- Add runtime checking of the settings file against the JSON Schema
- Added tests to confirm ERROR messages to stdout
- Updated some fixtures since the ansible-navigator.yml file was invalid
- Added the application version to the schema
- The schema check is currently deep within the configurator, the intention is to move it out as its own function when `--validate` is added.
> Runtime JSON Schema validation of settings file

- docs/changelog-fragments.d/1102.breaking.md
- src/ansible_navigator/configuration_subsystem/navigator_configuration.py
- src/ansible_navigator/configuration_subsystem/schema.py
- tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
This move the ansible.config entry to ansible.config.path, making room to move help-config
Incremental work to get the help-* entries out of the root
Related #1100
> Move `ansible.config` to `ansible.config.path`

- docs/changelog-fragments.d/1103.breaking.md
- src/ansible_navigator/configuration_subsystem/navigator_configuration.py
- src/ansible_navigator/configuration_subsystem/schema.py
- tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
This will make room to move help out of the root
> Move `ansible.invetories` to `ansible.inventory.paths`

- src/ansible_navigator/actions/run.py
This removes the UI check for valid inventory paths. This is because `ios101,` is valid.
Error handling will be done by ansible and the playbook will fail if an inventory does not exist.
> Remove check for inventory file path

- docs/changelog-fragments.d/1138.feature.md
- src/ansible_navigator/actions/images.py
- src/ansible_navigator/configuration_subsystem/configurator.py
- src/ansible_navigator/configuration_subsystem/definitions.py
- src/ansible_navigator/configuration_subsystem/navigator_configuration.py
- src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
- src/ansible_navigator/configuration_subsystem/transform.py
- src/ansible_navigator/package_data/settings-sample.template.yml
- src/ansible_navigator/package_data/settings-schema.partial.json
- tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/1.json
- tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/2.json
- tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/3.json
- tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
- tests/integration/actions/images/test_stdout_tmux.py
- tests/unit/configuration_subsystem/data.py
- tests/unit/configuration_subsystem/test_invalid_params.py
- Added tests
- Broke out the run_runner logic so it could be consumed by run_stdout
- Modified the check_choice function since `--details` can be a list, but has choices
- modified the `invalid choices` function so it could handle a list as well
- Added settings entry and post processor
- Modified the `to_schema` to place the enum inside of the item inside an array
- Updated the partial schema
- Updated the sample settings file
- Fixtures added as required
> Add the `--details` flag for `ansible-navigator images` for stdout

- .flake8
- src/ansible_navigator/ui_framework/__init__.py
- src/ansible_navigator/ui_framework/curses_defs.py
Removing .flake8 entries for src/ansible_navigator/ui_framework/__init__.py*curses_defs.py. 
Wanted to do more but need to jump out for the day and figured I would at least get it started.
> ui_framework init and curses_defs doc string fixes (D/DAR)

- .github/workflows/tox.yml
Reduce resource usage by running the no-test-deps env after normal unit (py) ones. Result is faster execution time.
> Optimize GHA execution

- tox.ini
- use default "py" to avoid forcing users to use py38
- correct external command to "sh" (error with tox4)
- ensure ANSI coloring works (tox4)
> Minor tox.ini fixes

- src/ansible_navigator/ui_framework/colorize.py
Fixes:
```
************ Module ansible_navigator.ui_framework.colorize
src/ansible_navigator/ui_framework/colorize.py:56:5: W1517: 'lru_cache(maxsize=None)' will keep all method args alive indefinitely, including 'self' (cache-max-size-none)
```
https://github.com/ansible/ansible-navigator/pull/1199
We should not see a large number of style scope combinations, so will leave it at the default of 128.
Tested locally, did not see notice any rendering speed changes
> Remove max size none for lru_cache

- .flake8
- .pre-commit-config.yaml
- requirements.txt
- setup.cfg
This fixes a problem where presence of this plugin caused errors on other projects, as we did
not have custom configuration for it.
Related: https://github.com/zheller/flake8-quotes/issues/105
> Remove flake8-quotes

- cspell.config.yaml
Related: https://github.com/ansible/ansible-navigator/issues/1221
Previously, compound words were enabled by default, cleanup can happen in the future
> Allow compound words for python

- src/ansible_navigator/configuration_subsystem/configurator.py
Fixes: #1224
In the case of `settings --sample` being directed to a settings file, allow it to be empty, but return immediately w/o processing it.
> Fix settings issue when directing to a settings file

- docs/conf.py
Resolving Sphinx incompatibilities with current extlinks.
Added "%s" keyword to the second tuples in the extlink caption strings as required by Sphinx 6.0. 
Resolves #1238 .
> Adding required keyword to sphinx extlink caption strings

- src/ansible_navigator/configuration_subsystem/navigator_configuration.py
- src/ansible_navigator/configuration_subsystem/utils.py
Python 3.11 is raising a ValueError because of the mutable default value:
```
/usr/lib64/python3.11/dataclasses.py:816: in _get_field
raise ValueError(f'mutable default {type(f.default)} for field '
E   ValueError: mutable default <class 'ansible_navigator.configuration_subsystem.utils.AnsibleConfiguration'> for field ansible_configuration is not allowed: use default_factory
```
Switch to using default_factory.
> Default factory for ApplicationConfiguration

- tests/unit/test_circular_imports.py
https://github.com/ansible/ansible-runner/issues/969  has been addressed
In py3.11 pipes throws a deprecation warning so https://github.com/ansible/ansible-runner/issues/1101 was raised and the exclusion updated.
> Update runner warning exclusion

- setup.cfg
Related: https://github.com/pypa/setuptools/pull/3276
Require a later version of setuptools for python 3.11 to avoid `sre_constants` deprecation warnings.
Additionally sort the list of requirements.
> Require later setuptools for python 3.11

- src/ansible_navigator/configuration_subsystem/definitions.py
- src/ansible_navigator/content_defs.py
- src/ansible_navigator/tm_tokenize/compiler.py
- src/ansible_navigator/tm_tokenize/reg.py
- src/ansible_navigator/tm_tokenize/rules.py
- src/ansible_navigator/tm_tokenize/state.py
- src/ansible_navigator/tm_tokenize/tokenize.py
- src/ansible_navigator/ui_framework/field_checks.py
- src/ansible_navigator/ui_framework/field_radio.py
- tests/integration/_cli2runner.py
- tests/integration/test_execution_environment.py
- tests/integration/test_execution_environment_image.py
- tests/integration/test_pass_environment_variable.py
- tests/integration/test_set_environment_variable.py
As the minimal version of python is py38, we can now avoid having to quote type hint information.
Reference: https://adamj.eu/tech/2021/05/15/python-type-hints-future-annotations/
Partial-Fix: https://github.com/ansible/devtools/issues/65
> Implement PEP-563

- tests/integration/test_stdout_exit_codes.py
The error from ansible 2.13.4 is:
```
ERROR! Missing name(s), incorrect options passed for detailed documentation.
```
in 2.12.4 it was:
```
ERROR! Incorrect options passed
```
> Ignore case of error

- tests/integration/_tmux_session.py
Prior to version 0.15 of libtmux, all empty lines were removed from the captured output. This restores that behavior to prep for that dependency upgrade.
Their change:
https://github.com/tmux-python/libtmux/pull/405/files
> Prep for libtmux version 0.15 +

- .pre-commit-config.yaml
This aligns the configuration of black with other devtools maintained projects.
Black will now reformat via precommit, instead of simply warning that it would have.
> Enable black formatting

- src/ansible_navigator/data/ansible-navigator.json
- src/ansible_navigator/diagnostics.py
- src/ansible_navigator/utils/write_json.py
- tests/integration/diagnostics/test_for_permissions.py
Summary :
- To ensure the diagnostics file is not written to a world readable location
- Setting the file permissions to user only before writing
> Diagnostics file permissions

- src/ansible_navigator/cli.py
Resolves: https://github.com/ansible/ansible-navigator/issues/1215
> Update exec action to return with correct exit code

- .config/Dockerfile
- .github/dependabot.yml
- src/ansible_navigator/configuration_subsystem/navigator_configuration.py
- src/ansible_navigator/data/default_ee_dockerfile
- src/ansible_navigator/utils/packaged_data.py
- tests/defaults.py
Ongoing work to centralize the default ee.
1) move the docker file to the source so it is packaged
2) update dependabot to look in that location for docker ecosystem
3) pull from that file for the runtime default
4) use runtime logic to provide the default for tests
additional PRs:
1) will remove the tox entry
2) put the pull in pytest for the default ee
3) move other image names into dockerfiles
4) get rid of the constant being set to a function :)
5) Move from quay to ghcr when centralized
> Source runtime and test image from dockerfile

- .config/dictionary.txt
- tests/conftest.py
- tests/integration/actions/builder/base.py
- tests/integration/actions/builder/test_stdout_tmux.py
- tox.ini
Ongoing work to centralize the default ee.
1. Use a session-scoped autorun fixture to pull the default EE
2. Remove that work from tox 
additional PRs:
1. move other image names into dockerfiles
2. get rid of the constant being set to a function :)
3. Move from quay to ghcr when centralized
related: #1358 
Note: This PR also limits the number of builder builds we perform, and increases the timeout, as this is a common place for CI failures
> Retrieve the default EE using pytest

- tests/conftest.py
REgardless of the need to pull, always print the image pull summary.  This will help with image caching debugging.
> Always print image prologue

- tests/integration/actions/images/test_direct_interactive_ee.py
- tests/integration/actions/images/test_direct_interactive_noee.py
- tests/integration/actions/images/test_welcome_interactive_ee.py
- tests/integration/actions/images/test_welcome_interactive_noee.py
- tests/integration/actions/inventory/test_direct_interactive_ee.py
- tests/integration/actions/inventory/test_direct_interactive_noee.py
- tests/integration/actions/inventory/test_welcome_interactive_ee.py
- tests/integration/actions/inventory/test_welcome_interactive_noee.py
- tests/integration/actions/run/test_direct_interactive_ee.py
- tests/integration/actions/run/test_direct_interactive_noee.py
- tests/integration/actions/run/test_welcome_interactive_ee.py
- tests/integration/actions/run/test_welcome_interactive_noee.py
- tests/integration/actions/templar/test_direct_interactive_ee.py
- tests/integration/actions/templar/test_direct_interactive_noee.py
- tests/integration/actions/templar/test_welcome_interactive_ee.py
- tests/integration/actions/templar/test_welcome_interactive_noee.py
**Summary**
- Use the `step_id_padded` function instead of `step_id` for getting index padded to 2 (i.e. 01-99 format)
- With this we can see the tests in correct order while using VSCode test tree.
> Arrange test-ids to order them correctly

- tests/integration/actions/templar/base.py
Rather than force vim-enhanced, we'll assume vi is installed and supports `-n`
Fixes #1381
> vim-minimal installs vi

- .vscode/launch.json
- This PR adds example configuration to debug ansible-navigator subcommands.
- Example of debugging `exec` subcommand is mentioned.
> Add more configuration entry in vscode settings

- tests/conftest.py
Quickly exit a test run if the pulling of images is not successful
also fixes the rendering of assessment errors
> Exit tests for failed pull

- tests/integration/test_stdout_exit_codes.py
Without being specified the default of `podman` was used.  This will allow the test to use the "valid" container engine for the system where the tests are being run.
This was identified while running tests on macos with docker.
> Use a valid container engine in exit code tests

- tests/conftest.py
- tests/integration/actions/doc/test_stdout_subprocess.py
`subprocess.run` with `capture_output` does not provide a TTY, when docker is run with `--tty` it will fail if running without a tty.
Continued work for macOS/docker testing
Note: navigator probably could have been run with `--pae false` to avoid pexpect mode in runner, but I thought this fixture would be handy to have in the future.
(https://github.com/ansible/ansible-runner/blob/e1509a0914b9157f0aebcc82fb99e7c2d4ad012e/ansible_runner/config/_base.py#L462)
> Provide a tty for stdout subprocess doc tests

- tests/integration/version_migration/test_v1_v2_settings.py
This test requires at least one 2. tag for the version.  Should rarely be a problem, but since I forgot to fetch all it's safe to assume I or someone else with do it again.
> Suggest a fetch all for settings migration test

- src/ansible_navigator/actions/collections.py
Closes #1265
This should identify if a collection found was in a volume mount.
All collections will be found in a xxxx/ansible_collections directory so we'll append ansible_collections as needed.
No tests are included, as json output for collections will be added and can be used to test this without tmux soon.
Related #1417
> Ensure volume mounted collections are identified as `bind_mount`

- README.md
ansible-navigator can be used on upstream Ansible, not just downsteam AAP
> ansible-navigator for all

- tests/conftest.py
Tests should be able to run even without a virtualenv.
> Remove check for virtualenv presence

- requirements.txt
`libtmux` - something changed related to screen width
`ansible-core` - ansible inventory output order appears to have changed
These should be upgraded after tests are green. 
Related #1450
> Down version for select deps

- .vscode/launch.json
- setup.cfg
- src/ansible_navigator/cli.py
- src/ansible_navigator/diagnostics.py
- src/ansible_navigator/utils/compatibility.py
- src/ansible_navigator/version.py
- tests/unit/test_circular_imports.py
Related: https://github.com/ansible/ansible-runner/issues/1223
`pkg_resources` is deprecated https://github.com/pypa/setuptools/blob/main/pkg_resources/__init__.py#L121
> Remove dep on pkg_resources, ignore runner err

- pyproject.toml
Fixes #1468 
Version 3 of navigator is getting pulled into 3.8.
```
m910x ➜  /tmp python3.8 -m venv venv
m910x ➜  /tmp source venv/bin/activate
(venv) m910x ➜  /tmp pip install ansible-navigator
Collecting ansible-navigator
Downloading ansible_navigator-3.0.1-py3-none-any.whl (299 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 299.9/299.9 kB 1.6 MB/s eta 0:00:00
```
This will trigger a release of 3.0.2 and a delete of 3.0.0 and 3.0.1 from pypi.
> Require py3.9 or later

- README.md
https://ansible-navigator.readthedocs.io/en/latest/installation returns 404, update and fix all readthedocs links.
> Fix readthedocs links

- .vscode/launch.json
Related to https://github.com/ansible/ansible-navigator/issues/628
> Add configuration entry for images, lint and run subcommands in vscode settings

- docs/faq.md
* The instructions created a shell variable that would not have been passed into execution environment causing the described process to fail
* A friend let me know the instructions were not working and I confirmed it myself locally (@penguinpages)
> Adjust Docs For Ansible Vault

- src/ansible_navigator/actions/exec.py
When running with a simple `ansible-navigator exec`
the command being generated was `/bin/bash -c` which quickly exits.
We will only now add the `-c` if extra paramters were found, otherwise simply run `/bin/bash`
> Fix for exec

- .vscode/launch.json
- src/ansible_navigator/actions/collections.py
- src/ansible_navigator/actions/images.py
- src/ansible_navigator/data/catalog_collections.py
The purestorage flasharray collection has a file in it's roles directory which was causing the catalog_collecitons script to fail.
Additionally, we were calling show instead of show form for a few of the notifications.
In the case of a complete failure of the collection catalog script, we will show a failure warning before the nothing found.
https://github.com/Pure-Storage-Ansible/FlashArray-Collection/tree/master/roles
Fixes #1482
> Fix issues while cataloging collections

- pyproject.toml
- src/ansible_navigator/tm_tokenize/compiler.py
- src/ansible_navigator/tm_tokenize/grammars.py
- src/ansible_navigator/tm_tokenize/reg.py
- src/ansible_navigator/tm_tokenize/region.py
- src/ansible_navigator/tm_tokenize/rules.py
- src/ansible_navigator/tm_tokenize/state.py
- src/ansible_navigator/tm_tokenize/tokenize.py
- src/ansible_navigator/tm_tokenize/utils.py
- src/ansible_navigator/utils/json_schema.py
- tests/smoke/no_test_dependencies.py
Fix to address **ruff: UP035**
For the built-in types like list, tuple, dict, etc. it is recommended to use the built-in types directly.
Example: `typing.List` is deprecated and `list` is preferred to use.
Similarly, `typing.Deque` class is deprecated and is replaced by the `collections.deque` class
> Improve type hinting

- pyproject.toml
- src/ansible_navigator/actions/images.py
Fix to address **ruff: G003**
As per: https://beta.ruff.rs/docs/rules/#flake8-logging-format-g, we should avoid using `+` and `f-string` while logging.
> Avoid f-string in logging statement

- pyproject.toml
- src/ansible_navigator/actions/_actions.py
- src/ansible_navigator/actions/back.py
- src/ansible_navigator/actions/collections.py
- src/ansible_navigator/actions/inventory.py
- src/ansible_navigator/actions/run.py
- src/ansible_navigator/cli.py
- src/ansible_navigator/configuration_subsystem/configurator.py
- src/ansible_navigator/configuration_subsystem/definitions.py
- src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
- src/ansible_navigator/data/catalog_collections.py
- src/ansible_navigator/image_manager/puller.py
- src/ansible_navigator/initialization.py
- src/ansible_navigator/ui_framework/colorize.py
- src/ansible_navigator/ui_framework/form.py
- src/ansible_navigator/ui_framework/form_handler_button.py
- src/ansible_navigator/ui_framework/form_handler_options.py
- src/ansible_navigator/ui_framework/ui.py
- src/ansible_navigator/ui_framework/utils.py
- src/ansible_navigator/ui_framework/validators.py
- src/ansible_navigator/utils/dict_merge.py
- src/ansible_navigator/utils/dot_paths.py
- src/ansible_navigator/utils/serialize.py
- src/ansible_navigator/utils/version_migration/definitions.py
- tests/integration/_common.py
- tests/integration/_tmux_session.py
- tests/integration/actions/doc/base.py
- tests/unit/actions/settings/test_settings.py
- tests/unit/configuration_subsystem/test_entries_sanity.py
- tests/unit/configuration_subsystem/test_invalid_params.py
Fix to address **ruff: SIM**
This PR covers: 
1. SIM102 - Use a single if statement instead of nested if statements
2. SIM105 - Use contextlib.suppress({exception}) instead of try-except-pass
3. SIM108 - Use ternary operator {contents} instead of if-else-block
4. SIM110 - Use {repl} instead of for loop
5. SIM114 - Combine if branches using logical or operator
6. SIM118 - Use {key} in {dict} instead of {key} in {dict}.keys()
7. SIM401 - Use {contents} instead of an if block
> Address SIM rule

- pyproject.toml
- src/ansible_navigator/action_base.py
- src/ansible_navigator/actions/inventory.py
- src/ansible_navigator/configuration_subsystem/configurator.py
- src/ansible_navigator/configuration_subsystem/definitions.py
- src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
- src/ansible_navigator/configuration_subsystem/parser.py
- src/ansible_navigator/steps.py
- src/ansible_navigator/tm_tokenize/compiler.py
- src/ansible_navigator/tm_tokenize/rules.py
- src/ansible_navigator/utils/dict_merge.py
- src/ansible_navigator/utils/dot_paths.py
- src/ansible_navigator/utils/serialize.py
- tests/conftest.py
- tests/integration/_common.py
- tests/integration/_tmux_session.py
- tests/integration/actions/builder/base.py
- tests/integration/actions/collections/base.py
- tests/integration/actions/config/base.py
- tests/integration/actions/doc/base.py
- tests/integration/actions/exec/base.py
- tests/integration/actions/images/base.py
- tests/integration/actions/inventory/base.py
- tests/integration/actions/settings/base.py
- tests/integration/settings_from_cli/test_json_schema_errors.py
- tests/smoke/no_test_dependencies.py
- tests/unit/actions/run/test_artifact.py
Fix to address **ruff: EM**
Exception must not use an string or f-string literal, assign to variable first
As per: https://beta.ruff.rs/docs/rules/#flake8-errmsg-em
> Exception must not use string or f-string literal

- tests/fixtures/common/collections/ansible_collections/company_name/coll_1/plugins/filter/coll_1.py
- tests/fixtures/common/collections/ansible_collections/company_name/coll_1/plugins/filter/filter_1.yml
- tests/fixtures/integration/actions/doc/test_direct_interactive_ee.py/test/filter_doc_pass/0.json
- tests/fixtures/integration/actions/doc/test_direct_interactive_noee.py/test/filter_doc_pass/0.json
- tests/fixtures/integration/actions/doc/test_stdout.py/test/filter_doc_with_ee/0.json
- tests/fixtures/integration/actions/doc/test_stdout.py/test/filter_doc_without_ee/0.json
- tests/fixtures/integration/actions/doc/test_welcome_interactive_ee.py/test/filter_doc_pass/0.json
- tests/fixtures/integration/actions/doc/test_welcome_interactive_ee.py/test/filter_doc_pass/1.json
- tests/fixtures/integration/actions/doc/test_welcome_interactive_noee.py/test/filter_doc_pass/0.json
- tests/fixtures/integration/actions/doc/test_welcome_interactive_noee.py/test/filter_doc_pass/1.json
- tests/integration/actions/doc/test_direct_interactive_ee.py
- tests/integration/actions/doc/test_direct_interactive_noee.py
- tests/integration/actions/doc/test_stdout.py
- tests/integration/actions/doc/test_welcome_interactive_ee.py
- tests/integration/actions/doc/test_welcome_interactive_noee.py
As the support for `filter` plugins are added with [PR](https://github.com/ansible/ansible-navigator/pull/1515).
Adding the tests and fixtures for sidecar filter plugin doc feature.
Closes: https://github.com/ansible/ansible-navigator/issues/617
> Test sidecar filter plugin doc

- pyproject.toml
- src/ansible_navigator/runner/ansible_config.py
- tests/integration/test_stdout_exit_codes.py
Related: https://github.com/ansible/ansible-runner/issues/1223
> Isolate navigator from ansible-runner internal warnings

- src/ansible_navigator/runner/base.py
Related: https://github.com/ansible/ansible-builder/issues/541
Related: https://github.com/ansible/ansible-navigator/issues/1448
Due to changes with the container build introduced with builder version 3, we will now run as user=root in a podman container.
See the builder issue above for details
> Set user to root with podman

- docs/faq.md
This is a suggestion of changes I would like to please see in the FAQ section _How can I use a vault password with ansible-navigator_.
relates to #1571 
* When I filed #1559 I was so focused on users not saving a vault password on disk that I overlooked the fact that the last two lines in that example need to be one line for it to function. 3ac92985a447b69169ffdc3f227983518f8dc40c addresses that
* at https://ansible.readthedocs.io/projects/navigator/faq/#how-can-i-use-a-vault-password-with-ansible-navigator the two options end up both being rendered as "1. …". 7b9b62799e528664b126939e1ef698ac70b3b2ad should address that.
* It could be useful to explain the env var option in a bit more depth, 1b4c64f98b8d27199280fda6cf262149510f5960 attempts to address that.
* When giving users 2 options, …
> suggested cleanups for vault password faq entry

- src/ansible_navigator/data/image_introspect.py
Related: #1582 #1580
This fixes some of the `:images` related issues with the given EE image: 
```
---
version: 3
images:
base_image:
name: quay.io/fedora/python-311:latest
dependencies:
ansible_core:
package_pip: ansible-core
ansible_runner:
package_pip: ansible-runner
galaxy:
collections:
- community.general
python:
- ansible-lint
```    
- Fixes the `list index out of range` error, when there is no entry inside PythonPackages.
- And hence one will be able to browse the other(1-5) entries inside images command like "General Information", "System Packages" etc, even if there is no entry inside "Python Packages".
> Fix image introspect for PythonPackages

- src/ansible_navigator/actions/collections.py
- src/ansible_navigator/actions/images.py
- src/ansible_navigator/data/image_introspect.py
Change the python_exec_path to `/usr/bin/python3`, so that python interpreter can find the site packages.
Fixes: https://github.com/ansible/ansible-navigator/issues/1582 and https://github.com/ansible/ansible-navigator/issues/1580
Related: https://github.com/ansible/ansible-builder/issues/589
> Change the python_exec path to /usr/bin/python3

- .github/CONTRIBUTING.md
- README.md
- Add the Contributing section to README
- Add a hint where docs source code is located
- CONTRIBUTING.md: add a hint
This solves an error I got when trying to run `pip install -e .\[test]`:
```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/aklychko/ansible-navigator
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```
> Contributing guidelines: improve

- pyproject.toml
- tests/integration/_tmux_session.py
- tox.ini
This change address a problem seen on MacOS where sequences of sendkeys() happens too quickly and causing failures.
On GHA we were not able to spot this issue, but on newer M1+ machines this seems to be a major source of test failures.
> Improve test execution on macos (tmux)

- tests/integration/actions/images/test_direct_interactive_noee.py
- tests/integration/actions/lint/base.py
- tests/integration/actions/run_unicode/base.py
- tests/unit/logger/test_time_zone.py
Reason: not really effective, especially for the UI multi-step tests.
> pytest: remove flaky reruns

- src/ansible_navigator/actions/images.py
- src/ansible_navigator/utils/functions.py
> More types (2)

- src/ansible_navigator/_version_doc_cache.py
This will allow the cache to be rebuild.
Related PR: https://github.com/ansible/ansible-navigator/pull/1738
> Update the version of collection doc cache

- .github/workflows/tox.yml
- .gitignore
- pyproject.toml
- tox.ini
- Archive coverage report from each job
- Combine coverage reports inside check job
- Make a single upload to codecov.io
[AAP-24264](https://issues.redhat.com/browse/AAP-24264)
> Refactor codecov to perform single coverage upload

- pyproject.toml
- src/ansible_navigator/actions/run.py
- src/ansible_navigator/logger.py
- tests/defaults.py
- tests/unit/actions/run/test_runner_async.py
Additionally addresses `N802` via a noqa, because function name `formatTime` can't be changed to a lowercase. Since its been derived from the class logging.LogRecord
> Address ruff `PIE810` and `N806`

- docs/faq.md
This fixes my mistake in documenting what I did at work and then documented by heart at home. 
Fixes: https://github.com/ansible/ansible-navigator/issues/1728
> Fix the documentation for securely passing the vault password

- docs/faq.md
- docs/index.md
Docs: change Getting started EE guide reference to point to the relevant location. The stuff was moved yesterday.
The old one currently refers to a 404 page
> Docs: change Getting started EE guide reference to point to the relevant location

- .github/dependabot.yml
- .github/workflows/tox.yml
- src/ansible_navigator/actions/images.py
Fixes: https://github.com/ansible/ansible-navigator/issues/1857 
The given command output before and after adding support for all available output formats:
```
ansible-navigator images --execution-environment-image community-ansible-dev-tools:latest --details system_packages --format json
```
Before: 
After:
> Allow images subcommand to display the resulting output in JSON format

- README.md
- src/ansible_navigator/utils/print.py
This is a very small correction in the print.py file to avoid after running `ansible-navigator images -m stdout` to have the prompt changed into colored and bold.
The issue is basically the following: when running the command from a linux machine with bash the prompt changes from this:
To this:
Related JIRA: https://issues.redhat.com/browse/AAP-36287
> [AAP-36287] fixing the end line code to revert the color

- .config/constraints.txt
- .gitignore
This PR updates `libtmux` to its latest version and also adds ansible temp directory (.ansible) to gitignore.
Related libtmux PR with the fix: https://github.com/tmux-python/libtmux/pull/562
> Fix CI: Update libtmux to the newer version

- src/ansible_navigator/actions/lint.py
**Affected navigator command -** `ansible-navigator lint tests/fixtures/integration/actions/lint`
**Problem -** In certain cases the 'location' dictionary contains a `positions` key instead of a `lines` key. This discrepancy raises a KeyError when trying to access issue["location"]["lines"]
**Fix -** The updated code now checks if the 'location' dictionary contains either the lines or positions key before attempting to access them. This prevents a `KeyError`
Related failures can be seen in these PRs: https://github.com/ansible/ansible-navigator/pull/1938, https://github.com/ansible/ansible-navigator/pull/1940
> Fix the lint subcommand failure: (KeyError: 'lines')

- src/ansible_navigator/actions/collections.py
Handle a case where the `doc` is a string and not a dictionary. 
Fixes: #1943 
Related: https://github.com/oVirt/ovirt-ansible-collection/issues/760
Here is the additional log information:
```
2025-04-08T14:34:37.777771+00:00 ERROR 'ansible_navigator.actions.collections._get_collection_plugins_details' Error getting short name from plugin doc /usr/share/ansible/collections/ansible_collections/redhat/rhv/plugins/test/ovirt_proxied_check.py
Traceback (most recent call last):
File "/home/bthornto/github/ansible-navigator/src/ansible_navigator/actions/collections.py", line 655, in _get_collection_plugins_details
short_name = plugin["doc"][plugin_type]
~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
2025-04-08T14:34:37.779031+00:00 DEBUG …
```
> Log and ignore malformed plugin doc string.

- tests/conftest.py
Due to multiple failures in the last days, we increase the timeout for this check.
See: https://github.com/ansible/ansible-navigator/actions/runs/14445957215/job/40506558418?pr=1952
> Increase container engine timeout

- .github/workflows/tox.yml
Previous implementation was failing on job reruns because we already merged existing reports.
> Make coverage file number check a warning

- .github/workflows/tox.yml
**To fix**: `Codecov: Failed to get OIDC token with url: https://codecov.io./ Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env`
Related CI failure: https://github.com/ansible/ansible-navigator/actions/runs/14475535640/job/40600202341?pr=1957
> Add `contents:read` permissions to tox workflow

- src/ansible_navigator/cli.py
- src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
- Fixes the `FileNotFoundError` for paths that do not exist.
- Moves the cache path generation outside of the loop (unrelated to the above error, just found and corrected it)
> Improve path normalization with a fallback for non-existent paths

- codecov.yml
- This PR adds an ignore section in codecov.yml to exclude some listed file and folder from its coverage analysis.
- This prevents the low coverage in caching scripts to negatively impact the overall coverage metrics in Codecov.
> Ignore the untracked files in the codecov scan

- .pre-commit-config.yaml
- pyproject.toml
- src/ansible_navigator/utils/compatibility.py
- src/ansible_navigator/utils/json_schema.py
- tests/integration/_common.py
> fix: ruff, mypy and pylint violations
