ansible/ansible-navigator

setup.cfg

noticed these when trying to install in Macos system python

fix 2 errors in setup.cfg

---

ansible_navigator/actions/explore.py

fixes https://github.com/ansible/ansible-navigator/issues/65#

fixes traceback for attempting to rerun from load command

---

ansible_navigator/__init__.py
ansible_navigator/action_runner.py
ansible_navigator/actions/collections.py
ansible_navigator/actions/config.py
ansible_navigator/actions/inventory.py
ansible_navigator/actions/run.py
ansible_navigator/cli_args.py
ansible_navigator/runner/api.py
ansible_navigator/tm_tokenize/compiler.py
ansible_navigator/tm_tokenize/grammars.py
ansible_navigator/tm_tokenize/reg.py
ansible_navigator/tm_tokenize/rules.py
ansible_navigator/tm_tokenize/tokenize.py
ansible_navigator/tm_tokenize/utils.py
ansible_navigator/ui_framework/colorize.py
ansible_navigator/ui_framework/menu_builder.py
ansible_navigator/ui_framework/ui.py
ansible_navigator/utils.py
ansible_navigator/web_xterm_js.py
ansible_navigator/yaml.py
requirements-test.txt
test-requirements.txt
tox.ini
zuul.yaml

Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/832

Enabling Zuul CI on ansible-navigator

---

ansible_navigator/actions/run.py
ansible_navigator/runner/api.py
tox.ini

*  When running within local env get the complete executable
path for `ansible-playbook`
*  Update docs
*  Fix linter issues

Fix ansible-playbook not found issue in local env

---

ansible_navigator/actions/config.py
ansible_navigator/actions/run.py
ansible_navigator/cli.py
ansible_navigator/cli_args.py
tests/unit/actions/test_config.py

Rename the destination variable for mode option
from navigator_mode to mode.

Rename navigator_mode to mode

---

tox.ini

Switch HOME to pass through in tox.ini

---

ansible_navigator/ui_framework/ui.py
test-requirements.txt
tests/unit/test_cli.py

Not sure why I didn't think of this yesterday, old habits.

Remove dep on pytest-mock, use builtin monkeypatch

---

ansible_navigator/ui_framework/utils.py

Fixes https://github.com/ansible/ansible-navigator/issues/134
Try to convert value to percentage only if column value exist
in return result from action

Fix issue with menu builder

---

ansible_navigator/cli.py
ansible_navigator/config.py
tests/unit/test_config.py

Config source as enum vs str

---

README.md

Change:
- Add a screenshot from asciinema to the readme for now.
- The actual asciinema it links to isn't great due to color themes.
Tickets:
- Fixes #132

[readme] Add screenshot

---

ansible_navigator/actions/config.py
ansible_navigator/actions/doc.py
ansible_navigator/cli.py
ansible_navigator/cli_args.py
ansible_navigator/runner/api.py

*  Add support for doc command to run in stdout mode
with EE enabled/disabled
*  Refactor doc command in interactvie mode to use runner
API's to fetch the plugin docs

Add support for doc command stdout mode

---

ansible_navigator/configuration_subsystem/parser.py
tests/unit/configuration_subsystem/test_navigator_configuration_previous_cli.py

The test use of Subset.NONE was missing, this covers it and removes an extra comment

Add missing test

---

ansible_navigator/actions/run.py
ansible_navigator/configuration_subsystem/navigator_configuration.py
tests/integration/actions/stdout/base.py
tests/unit/test_playbook_artifact_path.py

also disabled artifact creation for the stdout test
and fix the condition for args.playbook_artifact_enable is True, although not really possible, it's initial value is Constants.NOT_SET
Fixes #183

Remove relative ./ from artifact path, add simple tests

---

tests/integration/actions/config/base.py
tests/integration/actions/doc/base.py
tests/integration/actions/inventory/base.py
tests/integration/actions/load/base.py
tests/integration/actions/stdout/base.py

better reporting when errors occur
Fixes #217

Switch to unified diff in integration tests

---

tests/integration/actions/doc/base.py

Fix in doc integration test, mask to outside loop

---

ansible_navigator/app.py

Fixes #190 
The pre-configuration subsystem uplift was carried forward

Fix doc string in _update_args

---

ansible_navigator/actions/run.py

In the case we get a message from runner that has no "event" key

Handle a runner message without an event

---

ansible_navigator/configuration_subsystem/definitions.py

depends-on: https://github.com/ansible/ansible-navigator/pull/257
thx @relrod ! 
closes #229

[config] micro optimization as suggested

---

setup.cfg

Depends-On: https://github.com/ansible/ansible-navigator/pull/257

[setup] ansible-runner: Pin to 2.0.0a2

---

ansible_navigator/_version.py

version bump to 0.6.2

---

ansible_navigator/actions/collections.py

Fixes #241 
recreated, tested locally

[:collections] Default to 'missing' if collection version key missing

---

README.md

Fixes #275 
Closes #70
Not a complete README cleanup, but an easier installation approach for most

[readme] small README improvement, quick start with pip + venv

---

setup.cfg

[pkg] Update setup.cfg description to match repo about and 1st line of README

---

tests/integration/_interactions.py
tests/integration/actions/config/base.py
tests/integration/actions/config/test_direct_interactive_ee.py
tests/integration/actions/config/test_direct_interactive_noee.py
tests/integration/actions/config/test_stdout_tmux.py
tests/integration/actions/config/test_welcome_interactive_ee.py
tests/integration/actions/config/test_welcome_interactive_noee.py
tests/integration/actions/config/test_welcome_interactive_param_use.py
tests/integration/actions/config/test_welcome_interactive_specified_config.py

*  Refactor config command integration tests
to use common base classes.

Refactor config command integration tests

---

ansible_navigator/actions/config.py
ansible_navigator/actions/doc.py
ansible_navigator/actions/inventory.py
ansible_navigator/actions/run.py
ansible_navigator/configuration_subsystem/navigator_post_processor.py
ansible_navigator/utils.py
tests/integration/_common.py
tests/unit/configuration_subsystem/test_configurator.py
tests/unit/configuration_subsystem/test_invalid_params.py
tests/unit/configuration_subsystem/test_precedence.py
tests/unit/configuration_subsystem/test_previous_cli.py
tests/unit/test_cli.py

[all] Switch to `shutil.which` as `distutils` is deprecated

---

README.md
ansible_navigator/actions/sample_form.py
ansible_navigator/configuration_subsystem/configurator.py
ansible_navigator/configuration_subsystem/definitions.py
ansible_navigator/configuration_subsystem/navigator_configuration.py
ansible_navigator/image_manager/image_puller.py
ansible_navigator/runner/api.py
ansible_navigator/utils.py
ansible_navigator/yaml.py
docs/settings.rst
docs/subcommands.rst

A set of cosmetic docs and comment corrections

Cosmetic changes for docs

---

ansible_navigator/actions/sample_working.py
ansible_navigator/ui_framework/__init__.py
ansible_navigator/ui_framework/field_working.py
ansible_navigator/ui_framework/form.py
ansible_navigator/ui_framework/form_defs.py
ansible_navigator/ui_framework/form_handler_working.py
ansible_navigator/ui_framework/form_presenter.py
ansible_navigator/ui_framework/form_utils.py

This is a non blocking notification, the single field immediately returns and the while loop exited.
(no buttons)

[ui] non blocking notification

---

ansible_navigator/configuration_subsystem/navigator_configuration.py
docs/settings.rst
docs/subcommands.rst

[:images] Add images subcommand

---

ansible_navigator/actions/images.py

Use the nonblocking notification to show images are being found

[:images] Switch to a nonblocking notification vs content

---

ansible_navigator/actions/images.py

[:images] nonblocking notification when introspecting image

---

ansible_navigator/actions/collections.py
ansible_navigator/actions/images.py

Closes #350 
in the end, the extra spacing looked odd, will keep as single line

[ui] Remove extra spacing in notifications

---

ansible.cfg
ansible_navigator/actions/config.py
ansible_navigator/ui_framework/form_utils.py

Fixes #327 
- also add logic so the notification form text doesn't run off the screen

[:config] Handle config errors with a warning

---

ansible_navigator/actions/images.py

Fixes #374 
Still not great, but fixes the issue with the awxee

[:images] Use working_dir to detect if this is an EE

---

docs/settings.rst

[docs] note the dot the in the settings file name

---

ansible-navigator.yml
ansible_navigator/actions/doc.py

[:doc] Use playbook dir or CWD for playbook dir

---

setup.cfg

[setup]  Require > 2a < 3 runner version 

---

ansible_navigator/actions/run.py
ansible_navigator/utils.py

[:run] When an event is received with an ERROR! show a blocking notification

---

ansible_navigator/action_runner.py
ansible_navigator/actions/collections.py
ansible_navigator/actions/config.py
ansible_navigator/actions/doc.py
ansible_navigator/actions/images.py
ansible_navigator/actions/inventory.py
ansible_navigator/actions/run.py
ansible_navigator/configuration_subsystem/definitions.py
ansible_navigator/configuration_subsystem/navigator_configuration.py
ansible_navigator/configuration_subsystem/navigator_post_processor.py
ansible_navigator/ui_framework/__init__.py
ansible_navigator/ui_framework/colorize.py
ansible_navigator/ui_framework/curses_defs.py
ansible_navigator/ui_framework/curses_window.py
ansible_navigator/ui_framework/form.py
ansible_navigator/ui_framework/form_handler_button.py
ansible_navigator/ui_framework/form_handler_information.py
ansible_navigator/ui_framework/form_handler_options.py
ansible_navigator/ui_framework/form_handler_text.py
ansible_navigator/ui_framework/form_handler_working.py
ansible_navigator/ui_framework/form_presenter.py
ansible_navigator/ui_framework/menu_builder.py
ansible_navigator/ui_framework/ui.py
ansible_navigator/ui_framework/ui_config.py
ansible_navigator/utils.py
docs/settings.rst
tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
tests/unit/actions/test_config.py
tests/unit/configuration_subsystem/data.py
tests/unit/ui_framework/test_colorize.py

This is an initial go at `NO_COLOR` support using the techniques that @cidrblock and I discussed in a call yesterday.
Fixes #174 
Fixes #394

`NO_COLOR` support for accessibility

---

docs/settings.rst

[docs] Settings doc updates

---

ansible_navigator/cli.py
ansible_navigator/runner/api.py

*  Set ansible-runner logging to the log level
and file handler same as that of ansible-navigator
Fixes #344

Enable ansible-runner logging

---

ansible_navigator/_version.py

Bump version to 0.7.0 in main branch

---

setup.cfg

[setup] Correct classifier string

---

README.md

[docs] Add images to README

---

README.md
docs/faq.md

We can add as needed as organize over time, just wanting _something_ here for questions as they arise
Fixes #277 
Fixes #408
Fixes #409

[docs] Started faq

---

setup.cfg

*  Will depend on ansible-runner n - 1
till stable release is done so that
we get time to test ansible-runner
changes with navigator before alpha release

Update ansible-runner version

---

README.md
docs/faq.md

Change:
- Expand on some points in the README and (re)move some stuff.
Tickets:
- Fixes #235
- Fixes #236
- Closes #240

README rewrite

---

ansible_navigator/cli.py

related to #433
related to #261 
Although this won't fix the problem, it will avoid a traceback and provide some logs

Catch no share directory

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

* Shamelessly copied from https://github.com/ansible/ansible/tree/devel/.github/ISSUE_TEMPLATE
and customised for ansible-navigator

Add issue template

---

share/ansible_navigator/markdown/help.md

[:help] Add welcome page to help

---

ansible_navigator/_version.py

Depends on: https://github.com/ansible/ansible-navigator/pull/447

[release-1.0] Bump version to 1.0.0a2

---

docs/settings.rst
tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
utilities/doc_updater.py

Closes #470 
Fixes #474 
Subtle changes to make the sample settings file a little easier to work with
also- fix for the ----type above

[docs] Settings file formatting

---

setup.cfg

Fixes #453 
This set lower and upper major bounds for dependencies in an attempt to avoid breaking changes in the future
runner will need to be updated to a non beta version later

[setup] Set major version constraints

---

ansible_navigator/configuration_subsystem/navigator_configuration.py
docs/settings.rst
tests/defaults.py
tests/fixtures/unit/cli/ansible-navigator.yml
tests/unit/test_cli.py
tox.ini

Set final execution environment image name

---

setup.cfg

Leaving runner with constraints, as well as `onigurumacffi`

Relax versions

---

ansible_navigator/runner/api.py

Always random private_data_dir

---

setup.cfg

confirmation prior to it's 2.0.0 release

ansible-runner minimum version to 2rc3

---

setup.cfg

does what it says, won't pass until runner 2 is released

runner min version to 2

---

ansible_navigator/_version.py

immediately following the release main will move to 1.1.0a1

Allow main to pass through version 1.0.0

---

ansible_navigator/configuration_subsystem/navigator_configuration.py
docs/settings.rst
test-requirements.txt
tests/defaults.py
tests/fixtures/unit/cli/ansible-navigator.yml
tests/unit/test_cli.py
tox.ini

Fixes #527
Resolves #533
Resolves #538

Fix the CI failures with linting and outdated EE image

---

ansible_navigator/actions/inventory.py

Refactor the code to make it easier to add new options in the future
without adding more pylint suppressions/ignores.

Refactor inventory details collection to reduce branches and locals

---

README.md
setup.cfg

Add ansible-related extras to distribution package

---

docs/faq.md

Fixes https://github.com/ansible/ansible-navigator/issues/524
and a few spelling errors

Note use of stdout for vars prompt in the FAQ

---

docs/faq.md

Add FAQ entry for ssh keys

---

docs/faq.md

Correct FAQ formatting

---

src/ansible_navigator/action_runner.py

Remove leftover code from original use of arparse

---

src/ansible_navigator/actions/run.py
src/ansible_navigator/runner/__init__.py
src/ansible_navigator/runner/ansible_doc.py
src/ansible_navigator/runner/base.py
src/ansible_navigator/runner/command_async.py
src/ansible_navigator/runner/command_base.py

No material code changes, mostly doc wording and typographical fixes

Followup on PR comments in #623

---

src/ansible_navigator/runner/ansible_config.py
src/ansible_navigator/runner/ansible_doc.py
src/ansible_navigator/runner/ansible_inventory.py
src/ansible_navigator/runner/base.py
src/ansible_navigator/runner/command.py
src/ansible_navigator/runner/command_async.py
src/ansible_navigator/utils.py
tests/unit/test_utils.py

Fixes #633 
Given the change to human_time, add tests to confirm
linting fixes in the utils test file

[linting, tests] Type hinting clean up

---

tests/defaults.py
tests/unit/actions/test_config.py
tests/unit/actions/test_inventory.py
tests/unit/actions/test_run.py
tests/unit/configuration_subsystem/conftest.py
tests/unit/configuration_subsystem/test_container_engine_auto.py
tests/unit/configuration_subsystem/test_fixture_sanity.py
tests/unit/configuration_subsystem/test_invalid_params.py
tests/unit/configuration_subsystem/test_precedence.py
tests/unit/configuration_subsystem/test_previous_cli.py
tests/unit/configuration_subsystem/test_sample_configurations.py
tests/unit/configuration_subsystem/utils.py
tests/unit/test_cli.py
tests/unit/test_image_introspection.py
tests/unit/test_log_append.py
tests/unit/test_yaml.py

Related #643 
- does what it says
- several doc string/sentence fixes when seen

[tests] Fix pylint errors in `tests/unit`

---

src/ansible_navigator/_yaml.py
src/ansible_navigator/actions/_actions.py
src/ansible_navigator/steps.py
src/ansible_navigator/tm_tokenize/reg.py
src/ansible_navigator/tm_tokenize/utils.py
src/ansible_navigator/ui_framework/form_handler_text.py

Fixes #638 
Specify the reason for some `# type: ignore` statements, remove ignore statements that are needed

[typing] Clarify some type ignores, remove uneeded

---

tests/fixtures/common/collections/ansible_collections/testorg/coll_1/plugins/lookup/lookup_1.py
tests/fixtures/common/collections/ansible_collections/testorg/coll_1/plugins/modules/mod_1.py
tests/fixtures/common/collections/ansible_collections/testorg/coll_2/plugins/lookup/lookup_2.py
tests/fixtures/common/collections/ansible_collections/testorg/coll_2/plugins/modules/mod_2.py

Related #643 
- does what it says
- correct module docstrings where found

[tests] Fix pylint errors in `tests/fixtures`

---

src/ansible_navigator/actions/doc.py
src/ansible_navigator/actions/inventory.py
src/ansible_navigator/actions/run.py
src/ansible_navigator/configuration_subsystem/navigator_configuration.py
src/ansible_navigator/steps.py
src/ansible_navigator/ui_framework/ui.py
src/ansible_navigator/utils.py

[linting] Switch to f strings from format

---

src/ansible_navigator/configuration_subsystem/navigator_configuration.py
tests/defaults.py
tests/fixtures/unit/cli/ansible-navigator.yml
tests/unit/test_cli.py
tox.ini

*  Update default execution environment image
from `quay.io/ansible/ansible-navigator-demo-ee:0.6.0`
to `quay.io/ansible/creator-ee:v0.2.0`

change default execution environment image

---

src/ansible_navigator/actions/_actions.py

This was a 3.6 specific mypy complaint

[type] Ignore attr defined

---

docs/conf.py
src/ansible_navigator/__init__.py
src/ansible_navigator/_version.py
src/ansible_navigator/_yaml.py

depends-on: https://github.com/ansible/ansible-navigator/pull/671
- does what it says

[lint, type] Linting, docstring and type improvements in `_` files

---

src/ansible_navigator/_yaml.py

A long line snuck in from another PR

[lint] long line

---

docs/changelog-fragments.d/662.internal.md
docs/changelog-fragments.d/664.internal.md
tox.ini

Move global flake8 ignores to per-file

---

.pre-commit-config.yaml
docs/faq.md
licenses/LICENSE.source.json.json.txt
tests/fixtures/integration/execution_environment/ansible-navigator_disable_ee.yml
tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
tests/smoketests/scenarios/smoke-config.yml
tox.ini

Resolve existing trailing whitespaces and prevents introduction of new ones.

Fixed trailing whitespace

---

.pre-commit-config.yaml

Avoid spelling fixture dumps

---

.github/CONTRIBUTING.md
.pre-commit-config.yaml

This simply lists the current linters that are enforced.
links and more details can be added later

[docs] Small contributors guide update

---

.zuul.d/jobs.yaml
.zuul.d/project.yaml

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1265

zuul: enable testing with full py36-py310 range

---

docs/_ext/single_sourced_data.py
share/ansible_navigator/utils/catalog_collections.py
share/ansible_navigator/utils/image_introspect.py
src/ansible_navigator/actions/collections.py
src/ansible_navigator/actions/run.py
src/ansible_navigator/command_runner/command_runner.py
src/ansible_navigator/configuration_subsystem/configurator.py
src/ansible_navigator/configuration_subsystem/definitions.py
src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
src/ansible_navigator/runner/base.py
src/ansible_navigator/ui_framework/colorize.py
src/ansible_navigator/ui_framework/curses_window.py
src/ansible_navigator/ui_framework/field_button.py
src/ansible_navigator/ui_framework/field_text.py
src/ansible_navigator/ui_framework/field_working.py
src/ansible_navigator/ui_framework/form_defs.py
src/ansible_navigator/ui_framework/form_handler_text.py
src/ansible_navigator/ui_framework/sentinals.py
src/ansible_navigator/ui_framework/ui.py
src/ansible_navigator/ui_framework/utils.py
src/ansible_navigator/utils.py
tests/conftest.py
tests/integration/_action_run_test.py
tests/integration/_tmux_session.py
tests/unit/configuration_subsystem/test_configurator.py
tests/unit/configuration_subsystem/test_mode_subcommand_action.py
tests/unit/configuration_subsystem/test_precedence.py
tests/unit/configuration_subsystem/test_previous_cli.py
tests/unit/test_utils.py

There were reported by codespell, but we will need a couple of separated changes to address all of them, as we for example even have a spelling mistake in a module name. These are safe to merge as is.

Fixed various spelling errors

---

.github/ISSUE_TEMPLATE/bug_report.md
.pre-commit-config.yaml

- adds two known spellcheck errors to ignored words, with note
- reduces the exclude list to generated files
- fixes one last minor spellcheck error

More spellcheck fixes

---

src/ansible_navigator/__main__.py
src/ansible_navigator/action_runner.py
src/ansible_navigator/actions/_actions.py
src/ansible_navigator/actions/back.py
src/ansible_navigator/actions/config.py
src/ansible_navigator/actions/doc.py
src/ansible_navigator/actions/inventory.py
src/ansible_navigator/actions/run.py
src/ansible_navigator/app.py
src/ansible_navigator/cli.py
src/ansible_navigator/configuration_subsystem/configurator.py
src/ansible_navigator/configuration_subsystem/definitions.py
src/ansible_navigator/configuration_subsystem/parser.py
src/ansible_navigator/initialization.py
src/ansible_navigator/runner/__init__.py
src/ansible_navigator/runner/base.py
src/ansible_navigator/runner/command_base.py
src/ansible_navigator/steps.py
src/ansible_navigator/tm_tokenize/rules.py
src/ansible_navigator/ui_framework/colorize.py
src/ansible_navigator/ui_framework/curses_defs.py
src/ansible_navigator/ui_framework/field_text.py
src/ansible_navigator/ui_framework/form_presenter.py
src/ansible_navigator/ui_framework/form_utils.py
src/ansible_navigator/ui_framework/menu_builder.py
src/ansible_navigator/ui_framework/ui.py
src/ansible_navigator/ui_framework/ui_config.py
src/ansible_navigator/ui_framework/utils.py
src/ansible_navigator/utils.py

- fixed some silly mistakes
- capitalize some abbreviations

Fix spelling errors in `src`

---

src/ansible_navigator/actions/back.py
src/ansible_navigator/actions/filter.py
src/ansible_navigator/actions/help_doc.py
src/ansible_navigator/actions/open_file.py
src/ansible_navigator/actions/quit.py
src/ansible_navigator/actions/refresh.py
src/ansible_navigator/actions/replay.py
src/ansible_navigator/actions/rerun.py
src/ansible_navigator/actions/sample_form.py
src/ansible_navigator/actions/sample_notification.py
src/ansible_navigator/actions/sample_working.py
src/ansible_navigator/actions/save.py
src/ansible_navigator/actions/select.py
src/ansible_navigator/actions/serialize_json.py
src/ansible_navigator/actions/serialize_yaml.py
src/ansible_navigator/actions/stdout.py
src/ansible_navigator/actions/template.py
src/ansible_navigator/actions/welcome.py
src/ansible_navigator/actions/write_file.py

noticed it was missing in a few

[typing] Add `ApplicationConfiguration` to `__init__` in actions

---

share/ansible_navigator/utils/catalog_collections.py
share/ansible_navigator/utils/image_introspect.py

Seems some pylint errors were missed in the share directory.
No attempt was made to refactor the code, most were simply disabled.

[lint] Fix/disable pylint errors

---

docs/_ext/single_sourced_data.py
docs/conf.py

[lint] Fix lint errors in `docs` directory

---

src/ansible_navigator/actions/config.py
src/ansible_navigator/actions/open_file.py
src/ansible_navigator/utils.py

Related #539, #499
but does not unpin pylint version 
Not intended to resolve either of the above, but instead eliminate the pylint error.

[lint] Fix several lint errors

---

.zuul.d/project.yaml

As we fixed those jobs we need to ensure we also run them inside gate.

Add py36/py37 to zuul gate

---

test-requirements.txt
tox.ini

Fixes #539 
Might pass after https://github.com/ansible/ansible-navigator/issues/754

[lint] Unpin the pylint version

---

tox.ini

Assure that lint and lint-vetting sections are one after another.

tox: move lint-vetting section

---

.pre-commit-config.yaml
.pylintrc
test-requirements.txt
tox.ini

Unify calling pylint from different toxenvs

---

src/ansible_navigator/actions/run.py

Since the init params would never get used due to the way actions are called, they can be set during initialization rather than expecting to be passed in.
Add types as needed, and update string
The `flake8` file will be updated separated.

Update `__init__` `:run` action (doc string and params)

---

.github/workflows/tox.yml

Fix the GHA `check` job to treat skips as failures

---

.pre-commit-config.yaml
test-requirements.txt
tox.ini

Runs black with **same options** as before under pre-commit.

Make black run under pre-commit

---

.flake8

Clean-up was done in #651 
This updates the `.flake8` file to reflect those changes.

Documentation improvements in `_` files (D/DAR)

---

.flake8
src/ansible_navigator/action_runner.py

A majority of the work was done in #652.
Some additional information was added here about how navigator works since this file is so critical in the whole flow and the first step in bringing up the TUI.
doc strings updated to reflect parameters in function signature
descriptions updated to reflect functionality
fix spelling mistakes as encountered
This additionally allows for the removal of D* and DAR* exceptions from the flake8 configuration file for the file(s) modified in the PR.

Documentation improvements in `action_runner.py` file (D/DAR)

---

docs/changelog-fragments.d/764.bugfix.md
src/ansible_navigator/actions/collections.py
tests/fixtures/integration/actions/collections/test_direct_interactive_ee_with_volmount.py/test/0.json
tests/integration/actions/collections/base.py
tests/integration/actions/collections/test_direct_interactive_ee_with_volmount.py

Change:
- Ensure that when working in EEs, we don't forget our config-specified
volmounts.
Test Plan:
- local testing
Tickets:
- Fixes #764

[collections] append, not overwrite, EE volmounts

---

src/ansible_navigator/ui_framework/form_presenter.py

This removes some abbreviations in the UI form presenter.

Remove some abbreviations in form presenter

---

src/ansible_navigator/ui_framework/field_option.py

Replace the non-word `cbox` with `check_box` since, well, that's what it is :)

Replace ``cbox`` with ``check_box``

---

src/ansible_navigator/utils.py

This replaces a couple variable names in utils.py to more meaningful variable names.

Replace made-up words in utils

---

src/ansible_navigator/actions/collections.py
src/ansible_navigator/actions/inventory.py
src/ansible_navigator/actions/log.py
src/ansible_navigator/actions/open_file.py
src/ansible_navigator/actions/run.py

Unabbreviate/replace several words across actions

Improve some variable names in several actions

---

src/ansible_navigator/command_runner/command_runner.py
src/ansible_navigator/image_manager/inspector.py

- renamed and typed a couple functions
- Type changes as required
- docstring updates to accurately reflect the function signature
- Limit only passing commands to command runner such that it does not need type knowledge of it's callers

Command runner and image inspector spelling and type fixes

---

src/ansible_navigator/runner/command_async.py

This does not appear to be used....  I was unable to find it's history....

Remove unused eventq from runner/CommandAsync

---

tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/0.json
tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/1.json
tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/2.json
tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/3.json
tests/fixtures/integration/actions/exec/test_stdout_config_file.py/test/0.json
tests/fixtures/integration/actions/exec/test_stdout_config_file.py/test/1.json
tests/fixtures/integration/actions/exec/test_stdout_config_file.py/test/2.json
tests/integration/actions/exec/base.py
tests/integration/actions/exec/test_stdout_config_cli.py
tests/integration/actions/exec/test_stdout_config_file.py

- Replace look_fors with present
- Replace look_nots with absent
- Fixtures updates to reflect name change
Related https://github.com/ansible/ansible-navigator/pull/927

Update exec integration tests: look_fors, look_nots_ => present, absent

---

src/ansible_navigator/action_base.py
src/ansible_navigator/action_runner.py
src/ansible_navigator/actions/builder.py
src/ansible_navigator/actions/collections.py
src/ansible_navigator/actions/config.py
src/ansible_navigator/actions/doc.py
src/ansible_navigator/actions/exec.py
src/ansible_navigator/actions/help_doc.py
src/ansible_navigator/actions/images.py
src/ansible_navigator/actions/inventory.py
src/ansible_navigator/actions/log.py
src/ansible_navigator/actions/run.py
src/ansible_navigator/actions/sample_form.py
src/ansible_navigator/actions/sample_notification.py
src/ansible_navigator/actions/sample_working.py
src/ansible_navigator/actions/stdout.py
src/ansible_navigator/actions/template.py
src/ansible_navigator/actions/welcome.py

Partial #209 
This renames the `App` class to `ActionBase` as it better describes it's use.

Rename App to ActionBase

---

.flake8
src/ansible_navigator/action_base.py

- doc strings updated to reflect parameters in function signature
This additionally allows for the removal of D* and DAR* exceptions from the flake8 configuration file for the file(s) modified in the PR.  (corrected file name as well)
Noticed in #949

Docstring updates in action_base (D/DAR)

---

tests/integration/_action_run_test.py
tests/integration/_tmux_session.py
tests/unit/configuration_subsystem/data.py
tests/unit/test_circular_imports.py

Closes #647 
Some were able to be removed, the remainders had the error code added.

Remove type ignore, clarify others in tests

---

.flake8

Closes #721 
Adds a link an description to the issue.

Clarify E203 ignore in flake8 configuration file

---

src/ansible_navigator/actions/inventory.py
src/ansible_navigator/ui_framework/__init__.py
src/ansible_navigator/ui_framework/ui_constants.py

This add constants for the colors in use for the UI and implments them for inventory.
This will position us to change the rest and future PRs can use these.
An enum was tested here, but the type changes would have cascaded deep into the UI types.

Add constant colors and decorations for the UI, implement in inventory action.

---

.pre-commit-config.yaml

The only change in this is the precommit file.
This will incrementally add formatting with prettier by file type.
This should currently not be changing any files.

Incremental implementation of prettier

---

.flake8
tests/unit/utils/test_serialize_yaml.py

Remove old entry from flake8, the file was recently moved (#1012 )

Fix docstring in `test_serialize_yaml.py` in file (D/DAR)

---

src/ansible_navigator/configuration_subsystem/configurator.py
src/ansible_navigator/runner/command_base.py

Since we've added a `shlex_join` to utils, use that across the board.

Switch to internal shlex_join

---

docs/_ext/single_sourced_data.py
src/ansible_navigator/action_base.py
src/ansible_navigator/actions/collections.py
src/ansible_navigator/actions/open_file.py
src/ansible_navigator/actions/run.py
src/ansible_navigator/actions/template.py
src/ansible_navigator/actions/write_file.py
src/ansible_navigator/cli.py
src/ansible_navigator/configuration_subsystem/configurator.py
src/ansible_navigator/configuration_subsystem/definitions.py
src/ansible_navigator/configuration_subsystem/navigator_configuration.py
src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
src/ansible_navigator/configuration_subsystem/parser.py
src/ansible_navigator/image_manager/inspector.py
src/ansible_navigator/image_manager/puller.py
src/ansible_navigator/initialization.py
src/ansible_navigator/ui_framework/ui.py
src/ansible_navigator/utils/__init__.py
tests/unit/configuration_subsystem/conftest.py
tests/unit/configuration_subsystem/test_invalid_params.py
tests/unit/test_image_introspection.py
tests/unit/utils/test_functions.py

- This removes the wildcard import and directly imports from utils.functions where needed.

Update utils import statements to point to functions

---

docs/conf.py
src/ansible_navigator/actions/collections.py
src/ansible_navigator/configuration_subsystem/definitions.py
src/ansible_navigator/configuration_subsystem/navigator_configuration.py

Related typing and docs fixes as required.

Switch from `SimpleNamespace` to `dataclass` for `Internals`

---

src/ansible_navigator/cli.py

Test: Small change to test auto

---

.github/workflows/autoupdate.yml

Rename action, add label

---

src/ansible_navigator/cli.py

Test: Revert #1042

---

CHANGELOG.md

Hey @thedoubl3j & @webknjaz I have fixed this. Please review my PR.
Thanks!
#970

Fixed : broken changlog link #970

---

src/ansible_navigator/cli.py
tests/integration/test_stdout_exit_codes.py

Fixes #1052 
Introduced in #946 
No change log b/c it was never released.

Restore sys.exit with exit code

---

src/ansible_navigator/ui_framework/content_defs.py
src/ansible_navigator/utils/compatibility.py

Closes #1055 
Unanswered question?   How do we run check for this in the future? Hmm.

Limit the use of typing-extensions to just TYPE_CHECKING

---

.flake8
src/ansible_navigator/image_manager/__init__.py
src/ansible_navigator/image_manager/inspector.py
src/ansible_navigator/image_manager/puller.py

Removing .flake8 entries for src/ansible_navigator/image_manager and resolving flake8 docstring errors.

Docstring fixes for image_manager (D/DAR)

---

.flake8
src/ansible_navigator/command_runner/__init__.py
src/ansible_navigator/command_runner/command_runner.py

Removing .flake8 entries for src/ansible_navigator/command_runner and resolving flake8 docstring errors.

Docstring fixes for src/ansible_navigator/command_runner (D/DAR)

---

.flake8
src/ansible_navigator/steps.py

Removing .flake8 entries for src/ansible_navigator/steps.py and resolving flake8 docstring errors.

Docstring fixes for src/ansible_navigator/steps.py (D/DAR)

---

.flake8
src/ansible_navigator/initialization.py

Removing .flake8 entries for src/ansible_navigator/initialization.py and resolving flake8 docstring errors.

Docstring fixes for src/ansible_navigator/initialization.py (D/DAR)

---

.pre-commit-config.yaml
setup.cfg
src/ansible_navigator/cli.py
tests/unit/test_cli.py

Should help resolve issues related to versions.
e.g. #625

Include dependency versions and locations in debug log

---

src/ansible_navigator/configuration_subsystem/definitions.py
src/ansible_navigator/configuration_subsystem/navigator_post_processor.py

- also shifted the order around so Constants were at the top
- No code changes were made
- import statements updated as needed
Much of this ordering game can go away when 3.6 is dropped and postponed evaluation can be used

Move class definitions out of post processor into definitions

---

src/ansible_navigator/cli.py
src/ansible_navigator/logging.py

Just some clean-up after #1086

Move logger initialization out of cli.py

---

src/ansible_navigator/actions/collections.py
tests/integration/actions/collections/test_stdout_tmux.py

Reorder the conditional check such that self._collection cache is always a KeyValueStore
Update a couple docstring
Remove cast

Collection updates  (lint + typing)

---

src/ansible_navigator/actions/run.py

In the case of playbook completion without a single task, send the user to stdout for review.
Tested locally with successful and failing playbooks.

Redirect to `stdout` if a playbook completes without any tasks

---

docs/changelog-fragments.d/1144.feature.md
src/ansible_navigator/actions/images.py
tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/0.json
tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/1.json
tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/2.json
tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/3.json
tests/integration/actions/images/test_stdout_tmux.py
tests/integration/actions/inventory/test_direct_interactive_noee_errors.py

This uses the same approach as settings.

Allow images to syntax highlight stdout

---

.flake8
src/ansible_navigator/configuration_subsystem/__init__.py
src/ansible_navigator/configuration_subsystem/configurator.py
src/ansible_navigator/configuration_subsystem/definitions.py
src/ansible_navigator/configuration_subsystem/navigator_configuration.py
src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
src/ansible_navigator/configuration_subsystem/parser.py

Removing .flake8 entries for src/ansible_navigator/configuration_subsystem/* and resolving flake8 docstring errors. 
Also includes a few functions move to alias'.

Config subsystem docstrings (D/DAR) (again)

---

src/ansible_navigator/ui_framework/colorize.py
src/ansible_navigator/ui_framework/curses_defs.py
src/ansible_navigator/ui_framework/ui.py
src/ansible_navigator/ui_framework/ui_constants.py
tests/unit/ui_framework/test_colorize.py

Fixes #1020 
Previously font styles were not carried forward from tokenization to curses.
Future PRs will leverage this for styling the welcome and help pages.

Preserve font style

---

share/ansible_navigator/utils/image_introspect.py
src/ansible_navigator/image_manager/introspect.py

Fixes #824 
2 small fixes accounting for ansible 2.9
Changes made 2 both introspection scripts.

Small fixes for 2.9 (ansible version, collections list) 

---

docs/faq.md

Closes a long list of documentation updates and issues that have been waiting on 2.0 and the related FAQ entries.
Fixes #1066 
Fixes #1032 
Fixes #1021 
Fixes #945 
Fixes #868 
Fixes #829 
Fixes #620 
Fixes #618 
Fixes #610
Fixes #585
Fixes #491

FAQ updates

---

.flake8
src/ansible_navigator/ui_framework/form.py
src/ansible_navigator/ui_framework/form_defs.py
src/ansible_navigator/ui_framework/form_handler_button.py

Removing .flake8 entries for src/ansible_navigator/ui_framework/form,form_button_handler,form_defs.py

more ui_framework/form_* docstring updates (D/DAR) 

---

src/ansible_navigator/ui_framework/ui_constants.py

Fixes an issue with missing A_ITALIC on macOS

Italic fix on macOS

---

src/ansible_navigator/configuration_subsystem/definitions.py
src/ansible_navigator/configuration_subsystem/navigator_configuration.py
src/ansible_navigator/configuration_subsystem/transform.py

Add default values to be used when generating a schema, rather than having locally specific default values.

Add schema defaults

---

src/ansible_navigator/utils/ansi.py
src/ansible_navigator/utils/version_migration/definitions.py
src/ansible_navigator/utils/version_migration/migrate.py
src/ansible_navigator/utils/version_migration/settings_file.py
src/ansible_navigator/utils/version_migration/v1_v2_settings_file.py
tests/integration/version_migration/test_v1_v2_settings.py

- Change to "Press Enter"
- Don't print base class when looping through migrations

Migration fixes

---

src/ansible_navigator/configuration_subsystem/navigator_configuration.py

Fix string concatenation in `ansible-runner.timeout`

Typo fix (willforce)

---

tox.ini

Fixes lint-candidates after previous changes

Fix tox entry for lint-candidates

---

.config/dictionary.txt
.prettierignore
src/ansible_navigator/configuration_subsystem/transform.py
src/ansible_navigator/data/ansible-navigator.json
tox.ini

Add generated configuration schema file

---

.flake8
src/ansible_navigator/utils/functions.py

.flake8 entry removed for src/ansible_navigator/utils/functions.py and docstring fixes.

Docstring fixes for src/ansible_navigator/utils/functions.py

---

.flake8
src/ansible_navigator/data/__init__.py
src/ansible_navigator/ui_framework/form_handler_information.py
src/ansible_navigator/ui_framework/form_handler_options.py
src/ansible_navigator/ui_framework/form_handler_text.py
src/ansible_navigator/ui_framework/form_handler_working.py
src/ansible_navigator/ui_framework/form_utils.py

Doc strings updated/fixed for the form_*.py files as well as the settings schema file.

doc string additions for ui_framework/form* (D/DAR)

---

.flake8
src/ansible_navigator/ui_framework/field_button.py
src/ansible_navigator/ui_framework/field_checks.py
src/ansible_navigator/ui_framework/field_information.py
src/ansible_navigator/ui_framework/field_option.py
src/ansible_navigator/ui_framework/field_radio.py
src/ansible_navigator/ui_framework/field_text.py
src/ansible_navigator/ui_framework/field_working.py

.flake8 entry removed for src/ansible_navigator/ui_framework/field* and docstring fixes.

Docstring fixes for src/ansible_navigator/ui_framework/field* (D/DAR)

---

docs/_ext/single_sourced_data.py

Fix #1210 
rendered results "ansible-navigator subcommand overview" table.

backquotes cli example and subcommands

---

.flake8
src/ansible_navigator/data/ansible-navigator.json
tests/integration/actions/run/__init__.py
tests/integration/actions/run/base.py
tests/integration/actions/run/test_direct_interactive_ee.py
tests/integration/actions/run/test_direct_interactive_noee.py
tests/integration/actions/run/test_stdout_tmux.py
tests/integration/actions/run/test_welcome_interactive_ee.py
tests/integration/actions/run/test_welcome_interactive_noee.py

Removing flake8 entries for tests/integration/actions/run and docstring fixes.

Docstring fixes for tests/integration/actions/run (D/DAR)

---

.flake8
tests/integration/actions/stdout/__init__.py
tests/integration/actions/stdout/base.py
tests/integration/actions/stdout/test_direct_interactive_ee.py
tests/integration/actions/stdout/test_direct_interactive_noee.py
tests/integration/actions/stdout/test_welcome_interactive_ee.py
tests/integration/actions/stdout/test_welcome_interactive_noee.py

Removing flake8 entries and docstring fixes for tests/integration/actions/stdout.

Docstring fixes for tests/integration/actions/stdout (D/DAR)

---

.flake8
tests/integration/actions/templar/__init__.py
tests/integration/actions/templar/base.py
tests/integration/actions/templar/test_direct_interactive_ee.py
tests/integration/actions/templar/test_direct_interactive_noee.py
tests/integration/actions/templar/test_welcome_interactive_ee.py
tests/integration/actions/templar/test_welcome_interactive_noee.py

Removing flake8 entries and docstring fixes for tests/integration/actions/templar.

Docstring fixes for tests/integration/actions/templar (D/DAR)

---

.pre-commit-config.yaml

Adds darglint/flake8-docstrings to required checks.
Not all fixes have been completed but many have and work continues.

Require well formatted docstrings

---

.pre-commit-config.yaml

https://github.com/streetsidesoftware/cspell-cli/issues/170#issuecomment-1185602320

Fix pre-commit hook version

---

.pre-commit-config.yaml
CHANGELOG.md

Disable link-image-reference-definitions

---

src/ansible_navigator/configuration_subsystem/navigator_configuration.py

fix lint sub command version_added

---

.flake8
tests/unit/actions/collections/test_collection_doc_cache_path.py
tests/unit/actions/test_config.py
tests/unit/actions/test_inventory.py
tests/unit/image_manager/test_image_puller.py
tests/unit/test_cli.py
tests/unit/test_image_introspection.py
tests/unit/ui_framework/test_colorize.py
tests/unit/utils/test_functions.py

.flake8 entry removals and docstring fixes for files in tests/unit. Resolving the remainder of tests/unit/actions flake8 issues.

Fixing additional test docstrings (D/DAR)

---

.flake8
tests/unit/configuration_subsystem/conftest.py
tests/unit/configuration_subsystem/data.py
tests/unit/configuration_subsystem/test_broken_settings.py
tests/unit/configuration_subsystem/test_configurator.py
tests/unit/configuration_subsystem/test_container_engine_auto.py

Fixes for some unit tests written for the config subsystem. .flake8 entry removals and docstring fixes for files in tests/unit

More additional test docstrings (D/DAR)

---

docs/conf.py

- sort nitpick_ignore
- add extra entry for py311 (dataclass.InitVar)

Ensure docs build with py311

---

docs/conf.py
src/ansible_navigator/app_public.py
src/ansible_navigator/ui_framework/ui.py
tox.ini

Related: https://github.com/sphinx-doc/sphinx/issues/10400
Needed-By: #1275

Implement annotation workaround for sphinx

---

requirements.txt
tox.ini

- Update some ansible dependencies
- Update more test dependencies

Update test dependencies (2)

---

src/ansible_navigator/image_manager/puller.py

Add warning and debug log output for the image puller.

Better puller logging

---

src/ansible_navigator/data/ansible-navigator.json

Update version in schema

---

src/ansible_navigator/actions/images.py

Add a check for a label to determine if a container is an EE.
Related: https://github.com/ansible/ansible-builder/issues/424
Resolves #454

Add label check for EE

---

src/ansible_navigator/actions/images.py
src/ansible_navigator/cli.py

- This PR updates the label_check for containers that have no labels.
- Additionally cleans-up `pull_image` checks.

Update label_check for images

---

src/ansible_navigator/utils/packaged_data.py
tests/unit/utils/test_dockerfile.py

Limit the image lines to only a FROM line in the dockerfile
add some tests to check formatting and the # of FROM lines == the ImageEntry member count

Tighten up image name retrieval, add tests

---

tests/integration/actions/images/base.py
tests/integration/actions/images/test_direct_interactive_ee.py
tests/integration/actions/images/test_direct_interactive_noee.py
tests/integration/actions/images/test_welcome_interactive_ee.py
tests/integration/actions/images/test_welcome_interactive_noee.py

This should avoid issues if creator-ee latest is installed

Use version for filter

---

tests/conftest.py

Related #1368
Need to let this environment variable through for fixture updates

Allow fixture update env var

---

README.md

7 "a demo interface can be found on youtube" : capitalize "YouTube."
30 "of Ansible collections)." : Period should be inside parenthesis "collections.)"
58 "data in real-time" : Hyphen between "real" and "time" not needed
89 "Or, use the" : Comma after "Or" not needed

Light-Copy-Edit HM803

---

.pre-commit-config.yaml
.vscode/launch.json
.vscode/settings.json

Should allow for easier debugging and running of tests
Additionally allow json comments

Add vscode settings

---

tests/fixtures/integration/actions/exec/test_stdout_file.py/test/2.json
tests/integration/actions/exec/base.py

Mask out the hostname from the exec test fixture

Mask hostname from exec

---

src/ansible_navigator/data/images_dockerfile
tests/conftest.py
tests/integration/test_execution_environment_image.py

Preparation for creator-ee 12.3, remove some hard coded small image references since it will change to creator-base

Remove hard coded small image

---

tests/conftest.py

Ensure tmux is installed for testing

---

.vscode/settings.json

Enable flake8, mypy, and pylint for vscode

---

tests/integration/_tmux_session.py

Handle the initial session setup to account for zsh and some warnings on Mac when switching to bash

Improve session setup

---

src/ansible_navigator/actions/images.py

With the introduction of `creator-ee:v0.12.4`, we are only relying on the images labels to determine if it is an execution environment.
`podman image inspect` has both a root label key as well as a config.label key.
`docker image inspect` only provides the labels in the config key.
As a precaution, we will check both places to determine if an image is an execution environment.
Note: Tested locally on macOS with docker

Check config.label key

---

tests/integration/test_stdout_exit_codes.py

Run stdout exit code test with a TTY

---

.flake8
tests/conftest.py

This slowed me down in #1422 because flake8 wasn't checking it and reporting issues

Type and lint tests/conftest.py

---

src/ansible_navigator/data/ansible-navigator.json

Missed in #1420 
Typically found, currently disabled #1344 
Prevented by #1426

Add format to schema

---

.flake8
tests/integration/_common.py

Another file touched recently that needed some cleanup

Type hint and lint `tests/integration/_common.py`

---

.github/workflows/tox.yml
tox.ini

Remove 3.8 tests

---

tests/integration/actions/builder/test_stdout_tmux.py

Related: https://github.com/ansible/ansible-navigator/pull/1360

Re-enable builder tests

---

src/ansible_navigator/configuration_subsystem/transform.py
src/ansible_navigator/data/ansible-navigator.json

Fixes: https://github.com/ansible/ansible-navigator/issues/1512

Include only major version inside schema generation

---

pyproject.toml
src/ansible_navigator/action_base.py
src/ansible_navigator/actions/collections.py
tests/integration/actions/replay/test_direct_interactive_ee.py
tests/integration/actions/stdout/test_direct_interactive_ee.py
tests/integration/actions/stdout/test_direct_interactive_noee.py
tests/unit/actions/test_exec.py

Fix to address **ruff: ISC**
Explanation: https://beta.ruff.rs/docs/rules/#flake8-implicit-str-concat-isc

Address implicit and explicit string concatenation

---

pyproject.toml
src/ansible_navigator/cli.py
src/ansible_navigator/data/catalog_collections.py
src/ansible_navigator/data/image_introspect.py
src/ansible_navigator/diagnostics.py
src/ansible_navigator/image_manager/introspect.py
src/ansible_navigator/ui_framework/colorize.py
src/ansible_navigator/utils/version_migration/definitions.py
src/ansible_navigator/version.py

Fix to address **ruff: BLE**
We are using the blind exceptions only in cases where they are important to catch.

Address BLE rule

---

.config/requirements.in
requirements.txt

Check compatibility with latest version ([3.0.0rc2](https://github.com/ansible/ansible-builder/releases/tag/3.0.0rc2)) of ansible-builder.

Update ansible-builder version

---

tests/fixtures/common/builder/test_ee/execution-environment.yml

The latest builder release should support a dict for the galaxy key now

Switch to struct data for galaxy

---

.config/dictionary.txt
.pre-commit-config.yaml
docs/.generated/.gitignore
docs/_ext/regenerate_docs.py
tox.ini

Fix building of dynamic configuration section

---

.config/dictionary.txt
docs/faq.md

attempts to address #1559 
closes: #1559

fix vault file with env var

---

docs/faq.md
docs/index.md
src/ansible_navigator/configuration_subsystem/navigator_configuration.py

Add EE Getting started references to docs
Fixes https://github.com/ansible-community/community-team/issues/308

Add EE Getting started references to docs

---

src/ansible_navigator/data/ansible-navigator.json
src/ansible_navigator/data/settings-schema.partial.json

Needed-By: https://github.com/ansible/ansible-lint/pull/3684

Include documentation URL in JSON Schema

---

.config/requirements.in
requirements.txt

Needed for https://github.com/ansible/ansible-navigator/pull/1574

Update ansible-lint to 6.19.0

---

.github/workflows/tox.yml
pyproject.toml
requirements.txt
src/ansible_navigator/constants.py
src/ansible_navigator/data/catalog_collections.py
src/ansible_navigator/ui_framework/colorize.py
src/ansible_navigator/ui_framework/ui_config.py
src/ansible_navigator/utils/compatibility.py

Related: https://github.com/ansible/devtools/issues/143
Partial: https://github.com/ansible/ansible-navigator/issues/1610

Enable testing with python 3.12

---

docs/faq.md

Closes: https://github.com/ansible/ansible-navigator/issues/1595

Add FAQ entry for syntax-check

---

pyproject.toml
src/ansible_navigator/actions/lint.py
src/ansible_navigator/data/catalog_collections.py
src/ansible_navigator/diagnostics.py

Related: https://docs.astral.sh/ruff/rules/#flake8-datetimez-dtz
Blocks: https://github.com/ansible/ansible-navigator/pull/1622

Address `DTZ` rule

---

.pre-commit-config.yaml
pyproject.toml
src/ansible_navigator/data/ansible-navigator.json
tests/integration/version_migration/test_v1_v2_settings.py

Related: https://github.com/ansible/tox-ansible/issues/230
This PR also updates the version in schema file and required test after the first calver release.

Switch from darglint to pydoclint

---

tests/unit/actions/test_config.py
tests/unit/configuration_subsystem/post_processors/test_playbook_artifact_save_as.py
tests/unit/configuration_subsystem/test_settings_effective.py
tests/unit/logger/test_append.py
tests/unit/logger/test_time_zone.py

Related: https://github.com/ansible/ansible-navigator/issues/1660
There will be follow up PRs to address all the changes.

Fix some of the duplicate test names

---

.config/requirements-test.txt
pyproject.toml
requirements.txt

Update pytest-plus to 0.6.1

---

.github/workflows/tox.yml
codecov.yml

Related: https://github.com/ansible/team-devtools/issues/169

Review codecov configuration

---

.config/requirements-test.txt

Related: https://github.com/tmux-python/libtmux/issues/468

Prevent accidental use of incompatible libtmux

---

src/ansible_navigator/actions/config.py
src/ansible_navigator/configuration_subsystem/configurator.py
src/ansible_navigator/data/image_introspect.py
src/ansible_navigator/steps.py
src/ansible_navigator/ui_framework/colorize.py
src/ansible_navigator/ui_framework/form.py
src/ansible_navigator/ui_framework/form_handler_button.py
src/ansible_navigator/ui_framework/form_handler_options.py
src/ansible_navigator/ui_framework/form_handler_text.py
src/ansible_navigator/utils/version_migration/definitions.py
tests/smoke/no_test_dependencies.py
tests/unit/configuration_subsystem/post_processors/test_execution_environment_volume_mounts.py

More types

---

.config/constraints.txt
.config/dictionary.txt
.config/requirements-test.in
pyproject.toml
src/ansible_navigator/ui_framework/menu_builder.py
tests/conftest.py
tests/integration/actions/builder/base.py
tests/integration/actions/collections/base.py
tests/integration/actions/config/base.py
tests/integration/actions/doc/base.py
tests/integration/actions/doc/test_stdout_subprocess.py
tests/integration/actions/exec/base.py
tests/integration/actions/images/base.py
tests/integration/actions/inventory/base.py
tests/integration/actions/lint/base.py
tests/integration/actions/run/base.py
tests/integration/actions/run_unicode/base.py
tests/integration/actions/settings/base.py
tests/integration/actions/stdout/base.py
tests/integration/actions/templar/base.py
tests/integration/diagnostics/test_from_cli.py
tests/unit/configuration_subsystem/test_invalid_params.py
tests/unit/configuration_subsystem/test_posix_message_queue.py
tests/unit/utils/test_functions.py
tox.ini

- avoid polluting console when not in verbose mode
- stop trying extra step when on fails
- use tox native ability to install dependencies
Related: #1681

pytest: improve logging and reliability

---

docs/faq.md

This is a better way to use ansible vaults with ansible-navigator, I really didn't like the existing solutions, but actually one of them together with our usage of gpg inspired me, so here's the PR. :)

Improve the FAQ on how to use ansible vaults with ansible-navigator

---

pyproject.toml

drop setuptools_scm_git_archive

---

.config/constraints.txt
.github/workflows/tox.yml

Related: https://github.com/pytest-dev/pytest-plus/releases/tag/v0.7.0

Collect pytest logs

---

tests/conftest.py

Allow running the tests with default empty /etc/ansible/ansible.cfg file.

test: ignore empty /etc/ansible/ansible.cfg file

---

.github/workflows/release.yml
src/ansible_navigator/__main__.py
tests/fixtures/integration/actions/doc/test_direct_interactive_ee.py/test/module_doc_fail/0.json
tests/fixtures/integration/actions/doc/test_direct_interactive_noee.py/test/module_doc_fail/0.json
tox.ini

Committed via https://github.com/asottile/all-repos

Use python3 executable

---

pyproject.toml
src/ansible_navigator/tm_tokenize/__init__.py
src/ansible_navigator/tm_tokenize/fchainmap.py
src/ansible_navigator/tm_tokenize/rules.py
src/ansible_navigator/tm_tokenize/tokenize.py
src/ansible_navigator/tm_tokenize/utils.py

JIRA issue: https://issues.redhat.com/browse/AAP-23729

Address ruff `D`

---

pyproject.toml
src/ansible_navigator/actions/inventory.py
src/ansible_navigator/initialization.py
src/ansible_navigator/logger.py
src/ansible_navigator/utils/functions.py
tests/conftest.py
tests/integration/_common.py

There will be follow up PRs for other PTH rules.

Address ruff `PTH`

---

src/ansible_navigator/initialization.py
src/ansible_navigator/utils/functions.py
tests/defaults.py
tests/unit/configuration_subsystem/defaults.py
tests/unit/configuration_subsystem/test_internals.py
tests/unit/utils/test_functions.py

This fix is needed for `PTH110`.
Related [PR](https://github.com/ansible/ansible-navigator/pull/1781)

Pathlib conversion: find_settings_file

---

src/ansible_navigator/actions/lint.py
src/ansible_navigator/actions/run.py
src/ansible_navigator/configuration_subsystem/definitions.py
src/ansible_navigator/configuration_subsystem/navigator_configuration.py
src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
src/ansible_navigator/utils/functions.py
tests/unit/configuration_subsystem/test_settings_effective.py

Related PR: https://github.com/ansible/ansible-navigator/pull/1788

Use utility function `expand_path` instead of `abs_user_path`

---

src/ansible_navigator/cli.py

Fixes: [AAP-22511](https://issues.redhat.com/browse/AAP-22511)

Exit with an appropriate message if the image is invalid

---

.github/CODEOWNERS

chore: Update .github/CODEOWNERS

---

tox.ini

Related: https://github.com/tox-dev/tox-extra/issues/121

Temporary cap version of tox-extra

---

pyproject.toml
src/ansible_navigator/configuration_subsystem/navigator_post_processor.py

Fixes: #1958
Related: AAP-43297

Normalize ansible config path

---

.env
tests/conftest.py

Isolate navigator tests from user configuration

---

.github/workflows/tox.yml

This should solve forks not uploading
Also implement https://github.com/ansible/team-devtools/pull/293

chore: Fix codecov use_oidc setting

---

.github/workflows/tox.yml

Adopt coactions/upload-artifact
